[workspace]
resolver = "2"
members = [
    "openui-geometry",
    "openui-style",
    "openui-dom",
    "openui-layout",
    "openui-paint",
    "openui-compositor",
    "openui-engine",
    "openui-platform",
    "openui-ffi",
    "openui-text",
    "openui",
    "openui-macros",
    "examples/hello",
    "examples/counter",
    "examples/todo",
    "examples/dashboard",
    "pixel-compare",
]
exclude = ["fuzz"]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/zhuowcui/open-ui"
homepage = "https://github.com/zhuowcui/open-ui"
categories = ["gui", "rendering"]
keywords = ["ui", "desktop", "skia", "linux"]

[patch.crates-io]
skia-safe = { git = "https://github.com/rust-skia/rust-skia.git", rev = "a31b86ba3b767344d39af3b8c30043003d8fc991" }
skia-bindings = { git = "https://github.com/rust-skia/rust-skia.git", rev = "a31b86ba3b767344d39af3b8c30043003d8fc991" }
skrifa = { path = "vendor/skrifa-v0_40" }
read-fonts = { path = "vendor/read-fonts-v0_37" }
font-types = { path = "vendor/font-types-v0_11" }
bytemuck = { path = "vendor/bytemuck-v1" }
bytemuck_derive = { path = "vendor/bytemuck_derive-v1" }
