[workspace]
resolver = "2"
members = [
    "openui-geometry",
    "openui-style",
    "openui-dom",
    "openui-layout",
    "openui-paint",
    "openui-text",
    "openui-sys",
    "openui",
    "openui-macros",
    "openui-build",
    "examples/hello",
    "examples/counter",
    "examples/todo",
    "examples/dashboard",
    "pixel-compare",
]

[patch.crates-io]
skia-safe = { git = "https://github.com/rust-skia/rust-skia.git", rev = "c19a70ee1e5ea5a7790ee05a9b6f5fa3c05fae09" }
skia-bindings = { git = "https://github.com/rust-skia/rust-skia.git", rev = "c19a70ee1e5ea5a7790ee05a9b6f5fa3c05fae09" }
