#!/usr/bin/env python3
"""Generate the frozen Open UI v0.2 C ABI from the style and event schemas."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
STYLE_SCHEMA = ROOT / "bindings/rust/openui-style/property-schema.csv"
EVENT_SCHEMA = ROOT / "bindings/rust/openui-ffi/event-schema.csv"
HEADER_TEMPLATE = ROOT / "tools/ffi/openui.h.in"
HEADER_OUT = ROOT / "include/openui.h"
RUST_OUT = ROOT / "bindings/rust/openui-ffi/src/generated.rs"
MAP_OUT = ROOT / "bindings/rust/openui-ffi/openui.map"
SYMBOLS_OUT = ROOT / "docs/v02/generated/openui-ffi-symbols.txt"
LAYOUT_OUT = ROOT / "docs/v02/generated/openui-ffi-layout.json"
CHECKSUM_OUT = ROOT / "docs/v02/generated/openui-ffi-checksum.txt"


TAG_BY_KIND = {
    "display": 5,
    "position": 5,
    "overflow": 5,
    "length": 1,
    "edges": 6,
    "color": 4,
    "number": 2,
    "integer": 3,
    "flex-direction": 5,
    "flex-wrap": 5,
    "item-alignment": 5,
    "content-alignment": 5,
    "gap": 6,
    "font-family": 6,
    "font-weight": 2,
    "border": 6,
    "corner-radii": 6,
    "cursor": 5,
    "list-style": 5,
    "transform": 6,
    "pointer-events": 5,
    # Typography enums are transported as immutable compound handles. This
    # keeps the C ABI exhaustive as Chromium adds enum keywords while the
    # property ID still enforces the concrete Rust type at application time.
    "enum": 6,
    "compound": 6,
}


def read_rows(path: Path) -> list[dict[str, str]]:
    rows = list(csv.DictReader(path.read_text(encoding="utf-8").splitlines()))
    ids = [int(row["id"]) for row in rows]
    if ids != sorted(ids) or len(ids) != len(set(ids)):
        raise SystemExit(f"schema IDs must be unique and ordered: {path}")
    return rows


def generated_header(events: list[dict[str, str]]) -> bytes:
    event_enum = "\n".join(
        f"  {row['c_name']} = {row['id']}," for row in events
    )
    return HEADER_TEMPLATE.read_text(encoding="utf-8").replace(
        "@EVENT_ENUM@", event_enum
    ).encode()


def generated_rust(
    styles: list[dict[str, str]], events: list[dict[str, str]]
) -> bytes:
    properties = "\n".join(
        f"        {row['id']} => Some(StyleProperty::{row['rust_name']}),"
        for row in styles
    )
    tags = "\n".join(
        f"        StyleProperty::{row['rust_name']} => {TAG_BY_KIND[row['value_kind']]},"
        for row in styles
    )
    event_numbers = [int(row["id"]) for row in events]
    if event_numbers == list(range(event_numbers[0], event_numbers[-1] + 1)):
        event_ids = f"{event_numbers[0]}..={event_numbers[-1]}"
    else:
        event_ids = " | ".join(str(value) for value in event_numbers)
    text = f'''// @generated by tools/ffi/generate_ffi.py; do not edit.

use openui_style::StyleProperty;

pub(crate) fn property_from_raw(value: i32) -> Option<StyleProperty> {{
    match value {{
{properties}
        _ => None,
    }}
}}

pub(crate) fn expected_value_tag(property: StyleProperty) -> u32 {{
    match property {{
{tags}
    }}
}}

pub(crate) fn valid_event_type(value: u32) -> bool {{
    matches!(value, {event_ids})
}}
'''
    return text.encode()


def exported_symbols(header: bytes) -> list[str]:
    text = header.decode()
    symbols = re.findall(r"^(?:uint32_t|size_t|const uint8_t\*|OuiStatus)\s+(oui_[a-z0-9_]+)\s*\(", text, re.MULTILINE)
    if len(symbols) != len(set(symbols)):
        raise SystemExit("duplicate exported symbol declaration")
    return sorted(symbols)


def outputs() -> dict[Path, bytes]:
    styles = read_rows(STYLE_SCHEMA)
    events = read_rows(EVENT_SCHEMA)
    header = generated_header(events)
    rust = generated_rust(styles, events)
    symbols = exported_symbols(header)
    symbol_text = "".join(f"{symbol}\n" for symbol in symbols).encode()
    version_map = (
        "OPENUI_0.2 {\n  global:\n"
        + "".join(f"    {symbol};\n" for symbol in symbols)
        + "  local: *;\n};\n"
    ).encode()
    layouts = {
        "abi_version": "0x00020000",
        "pointer_width": 64,
        "types": {
            "OuiUtf8": {"size": 16, "align": 8},
            "OuiLength": {"size": 8, "align": 4},
            "OuiColor": {"size": 4, "align": 1},
            "OuiStylePayload": {"size": 8, "align": 8},
            "OuiStyleValue": {"size": 16, "align": 8},
            "OuiAppConfig": {"size": 40, "align": 8},
            "OuiAppRunConfig": {"size": 32, "align": 8},
            "OuiPlatformEvent": {"size": 152, "align": 8},
            "OuiViewportMetrics": {"size": 40, "align": 8},
            "OuiDocumentConfig": {"size": 48, "align": 8},
            "OuiTextRasterConfigurationV1": {"size": 16, "align": 4},
            "OuiRasterConfigurationV1": {"size": 72, "align": 4},
            "OuiScrollMetricsV1": {"size": 40, "align": 8},
            "OuiFontUnicodeRange": {"size": 8, "align": 4},
            "OuiFontFeatureDefault": {"size": 8, "align": 4},
            "OuiFontFaceDescriptor": {"size": 112, "align": 8},
            "OuiFontFaceInfo": {"size": 152, "align": 8},
            "OuiRect": {"size": 16, "align": 4},
            "OuiBitmap": {"size": 32, "align": 8},
            "OuiTransformOperation": {"size": 48, "align": 4},
            "OuiEasing": {"size": 48, "align": 8},
            "OuiAnimationOptions": {"size": 104, "align": 8},
            "OuiAnimationTimeline": {"size": 40, "align": 8},
            "OuiKeyframe": {"size": 80, "align": 8},
            "OuiAnimationState": {"size": 48, "align": 8},
            "OuiAnimationEvent": {"size": 48, "align": 8},
            "OuiEvent": {"size": 88, "align": 8},
            "OuiAccessibilityUpdate": {"size": 40, "align": 8},
            "OuiAccessibilitySnapshotInfo": {"size": 56, "align": 8},
            "OuiAccessibilityNodeInfo": {"size": 120, "align": 8},
            "OuiAccessibilityNodeState": {"size": 112, "align": 8},
            "OuiErrorInfo": {"size": 24, "align": 8},
        },
    }
    layout = (json.dumps(layouts, indent=2, sort_keys=True) + "\n").encode()
    digest = hashlib.sha256(header + rust + symbol_text + layout).hexdigest()
    checksum = f"sha256:{digest}\n".encode()
    return {
        HEADER_OUT: header,
        RUST_OUT: rust,
        MAP_OUT: version_map,
        SYMBOLS_OUT: symbol_text,
        LAYOUT_OUT: layout,
        CHECKSUM_OUT: checksum,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = outputs()
    if args.check:
        drift = [
            str(path.relative_to(ROOT))
            for path, data in generated.items()
            if not path.is_file() or path.read_bytes() != data
        ]
        if drift:
            raise SystemExit("generated FFI drift: " + ", ".join(drift))
        print(f"v0.2 C ABI: artifacts={len(generated)} drift=0")
        return
    for path, data in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    print(
        f"v0.2 C ABI: properties={len(read_rows(STYLE_SCHEMA))} "
        f"events={len(read_rows(EVENT_SCHEMA))} artifacts={len(generated)}"
    )


if __name__ == "__main__":
    main()
