//! Thread-local render context for the `view!` macro.
//!
//! The render context stores a pointer to the current [`Document`] so that
//! code generated by the `view!` macro can create elements without passing
//! the document explicitly.
//!
//! # Safety contract
//!
//! The [`Document`] reference passed to [`with_document`] must outlive all
//! effects and reactive subscriptions created during the render scope.
//! In practice this means the document should live for the program's
//! lifetime.

use crate::document::Document;
use std::cell::RefCell;

thread_local! {
    static RENDER_DOC: RefCell<Option<*const Document>> = const { RefCell::new(None) };
}

/// Execute `f` with `doc` as the current render document.
///
/// Inside `f` (and in any effects created during `f`), calling
/// [`current_document`] returns a reference to `doc`.
///
/// The document pointer is intentionally **not** cleared after `f` returns
/// so that reactive effects created during the scope can still access the
/// document when they re-execute.
///
/// # Safety
///
/// The caller must ensure `doc` outlives all reactive effects created
/// during the scope.
pub fn with_document<R>(doc: &Document, f: impl FnOnce() -> R) -> R {
    RENDER_DOC.with(|cell| {
        *cell.borrow_mut() = Some(doc as *const Document);
    });
    f()
}

/// Get the current render document.
///
/// # Panics
///
/// Panics if called outside a [`with_document`] scope (i.e. before any
/// document has been set).
pub fn current_document() -> &'static Document {
    RENDER_DOC.with(|cell| {
        let ptr = cell
            .borrow()
            .expect("current_document() called outside of with_document() scope");
        unsafe { &*ptr }
    })
}
