// @generated by tools/style/generate_properties.py; do not edit.

use crate::style::Error;
use crate::typed_style::*;
use crate::Element;

#[rustfmt::skip]
impl Element {
    pub fn set_display(&self, value: Display) -> Result<(), Error> {
        self.set_property(StyleProperty::Display, value.into())
    }
    pub fn set_position(&self, value: Position) -> Result<(), Error> {
        self.set_property(StyleProperty::Position, value.into())
    }
    pub fn set_overflow(&self, value: Overflow) -> Result<(), Error> {
        self.set_property(StyleProperty::Overflow, value.into())
    }
    pub fn set_width(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::Width, value.into())
    }
    pub fn set_height(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::Height, value.into())
    }
    pub fn set_min_width(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MinWidth, value.into())
    }
    pub fn set_min_height(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MinHeight, value.into())
    }
    pub fn set_max_width(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MaxWidth, value.into())
    }
    pub fn set_max_height(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MaxHeight, value.into())
    }
    pub fn set_margin(&self, value: Edges<LengthValue>) -> Result<(), Error> {
        self.set_property(StyleProperty::Margin, value.into())
    }
    pub fn set_margin_top(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MarginTop, value.into())
    }
    pub fn set_margin_right(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MarginRight, value.into())
    }
    pub fn set_margin_bottom(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MarginBottom, value.into())
    }
    pub fn set_margin_left(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::MarginLeft, value.into())
    }
    pub fn set_padding(&self, value: Edges<LengthValue>) -> Result<(), Error> {
        self.set_property(StyleProperty::Padding, value.into())
    }
    pub fn set_padding_top(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::PaddingTop, value.into())
    }
    pub fn set_padding_right(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::PaddingRight, value.into())
    }
    pub fn set_padding_bottom(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::PaddingBottom, value.into())
    }
    pub fn set_padding_left(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::PaddingLeft, value.into())
    }
    pub fn set_background_color(&self, value: Color) -> Result<(), Error> {
        self.set_property(StyleProperty::BackgroundColor, value.into())
    }
    pub fn set_color(&self, value: Color) -> Result<(), Error> {
        self.set_property(StyleProperty::Color, value.into())
    }
    pub fn set_opacity(&self, value: f32) -> Result<(), Error> {
        self.set_property(StyleProperty::Opacity, value.into())
    }
    pub fn set_z_index(&self, value: i32) -> Result<(), Error> {
        self.set_property(StyleProperty::ZIndex, value.into())
    }
    pub fn set_flex_direction(&self, value: FlexDirection) -> Result<(), Error> {
        self.set_property(StyleProperty::FlexDirection, value.into())
    }
    pub fn set_flex_wrap(&self, value: FlexWrap) -> Result<(), Error> {
        self.set_property(StyleProperty::FlexWrap, value.into())
    }
    pub fn set_flex_grow(&self, value: f32) -> Result<(), Error> {
        self.set_property(StyleProperty::FlexGrow, value.into())
    }
    pub fn set_flex_shrink(&self, value: f32) -> Result<(), Error> {
        self.set_property(StyleProperty::FlexShrink, value.into())
    }
    pub fn set_flex_basis(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::FlexBasis, value.into())
    }
    pub fn set_align_items(&self, value: ItemAlignment) -> Result<(), Error> {
        self.set_property(StyleProperty::AlignItems, value.into())
    }
    pub fn set_justify_content(&self, value: ContentAlignment) -> Result<(), Error> {
        self.set_property(StyleProperty::JustifyContent, value.into())
    }
    pub fn set_gap(&self, value: Gap) -> Result<(), Error> {
        self.set_property(StyleProperty::Gap, value.into())
    }
    pub fn set_row_gap(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::RowGap, value.into())
    }
    pub fn set_column_gap(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::ColumnGap, value.into())
    }
    pub fn set_font_family(&self, value: FontFamilyList) -> Result<(), Error> {
        self.set_property(StyleProperty::FontFamily, value.into())
    }
    pub fn set_font_size(&self, value: LengthValue) -> Result<(), Error> {
        self.set_property(StyleProperty::FontSize, value.into())
    }
    pub fn set_font_weight(&self, value: FontWeight) -> Result<(), Error> {
        self.set_property(StyleProperty::FontWeight, value.into())
    }
    pub fn set_border(&self, value: Border) -> Result<(), Error> {
        self.set_property(StyleProperty::Border, value.into())
    }
    pub fn set_border_top(&self, value: Border) -> Result<(), Error> {
        self.set_property(StyleProperty::BorderTop, value.into())
    }
    pub fn set_border_right(&self, value: Border) -> Result<(), Error> {
        self.set_property(StyleProperty::BorderRight, value.into())
    }
    pub fn set_border_bottom(&self, value: Border) -> Result<(), Error> {
        self.set_property(StyleProperty::BorderBottom, value.into())
    }
    pub fn set_border_left(&self, value: Border) -> Result<(), Error> {
        self.set_property(StyleProperty::BorderLeft, value.into())
    }
    pub fn set_border_radius(&self, value: CornerRadii) -> Result<(), Error> {
        self.set_property(StyleProperty::BorderRadius, value.into())
    }
    pub fn set_cursor(&self, value: Cursor) -> Result<(), Error> {
        self.set_property(StyleProperty::Cursor, value.into())
    }
    pub fn set_list_style(&self, value: ListStyleType) -> Result<(), Error> {
        self.set_property(StyleProperty::ListStyleType, value.into())
    }
    pub fn set_transform(&self, value: TransformList) -> Result<(), Error> {
        self.set_property(StyleProperty::Transform, value.into())
    }
}
