[package]
name = "openui-compositor"
version.workspace = true
edition.workspace = true
description = "Immutable scene snapshots and rendering backends for Open UI"
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
openui-layout = { version = "=0.2.0", path = "../openui-layout" }
openui-paint = { version = "=0.2.0", path = "../openui-paint" }
skia-safe = "0.94"

[dev-dependencies]
openui-dom = { version = "=0.2.0", path = "../openui-dom" }
