#!/usr/bin/env python3
"""Generate Rust, C, and reference tables from the canonical style schema."""

from __future__ import annotations

import argparse
import csv
import io
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "bindings/rust/openui-style/property-schema.csv"
RUST_OUT = ROOT / "bindings/rust/openui-style/src/generated_properties.rs"
C_OUT = ROOT / "include/openui_style_properties.h"
DOC_OUT = ROOT / "docs/v02/generated/style-properties.md"
FRAMEWORK_OUT = ROOT / "bindings/rust/openui/src/generated_style_setters.rs"

# Frozen from Chromium 147.0.7727.24's css_properties.json5 after excluding
# descriptors, SVG-only properties, and non-stable runtime flags. Keeping the
# set here makes a missing public typography property a generator/CI failure.
CHROMIUM_147_TYPOGRAPHY = frozenset(
    """
    -webkit-font-smoothing direction font font-family font-feature-settings
    font-kerning font-language-override font-optical-sizing font-palette
    font-size font-size-adjust font-stretch font-style font-synthesis
    font-synthesis-small-caps font-synthesis-style font-synthesis-weight
    font-variant font-variant-alternates font-variant-caps
    font-variant-east-asian font-variant-emoji font-variant-ligatures
    font-variant-numeric font-variant-position font-variation-settings
    font-weight hyphenate-character hyphenate-limit-chars hyphens
    initial-letter letter-spacing line-break line-height overflow-wrap
    ruby-align ruby-position tab-size text-align text-align-last text-autospace
    text-box text-box-edge text-box-trim text-combine-upright text-decoration
    text-decoration-color text-decoration-line text-decoration-skip-ink
    text-decoration-style text-decoration-thickness text-emphasis
    text-emphasis-color text-emphasis-position text-emphasis-style text-indent
    text-justify text-orientation text-overflow text-rendering text-shadow
    text-size-adjust text-spacing-trim text-transform text-underline-offset
    text-underline-position text-wrap text-wrap-mode text-wrap-style
    unicode-bidi vertical-align white-space white-space-collapse word-break
    word-spacing word-wrap writing-mode
    """.split()
)


def rows() -> list[dict[str, str]]:
    parsed = list(csv.DictReader(SCHEMA.read_text().splitlines()))
    ids = [int(row["id"]) for row in parsed]
    names = [row["css_name"] for row in parsed]
    if ids != sorted(ids) or len(ids) != len(set(ids)) or len(names) != len(set(names)):
        raise SystemExit("style schema IDs and names must be unique and ordered")
    missing_typography = sorted(CHROMIUM_147_TYPOGRAPHY.difference(names))
    if missing_typography:
        raise SystemExit(
            "style schema is missing Chromium 147 typography properties: "
            + ", ".join(missing_typography)
        )
    return parsed


def title(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("-"))


def screaming(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def rust_method(value: str) -> str:
    return value.strip("-").replace("-", "_")


def rust_output(schema: list[dict[str, str]]) -> bytes:
    variants = "\n".join(f"    {row['rust_name']} = {row['id']}," for row in schema)
    metadata = "\n".join(
        "\n".join(
            (
                "    PropertyMetadata {",
                f"        property: StyleProperty::{row['rust_name']},",
                f"        css_name: \"{row['css_name']}\",",
                f"        rust_type: \"{row['rust_type']}\",",
                f"        value_kind: ValueKind::{title(row['value_kind'])},",
                f"        initial: \"{row['initial']}\",",
                f"        inherited: {row['inherited']},",
                f"        invalidation: InvalidationClass::{title(row['invalidation'])},",
                f"        interpolation: InterpolationKind::{title(row['interpolation'])},",
                "    },",
            )
        )
        for row in schema
    )
    lookups = "\n".join(
        f'            "{row["css_name"]}" => Some(Self::{row["rust_name"]}),' for row in schema
    )
    builders = "\n".join(
        "\n".join(
            (
                f"    pub fn {rust_method(row['css_name'])}(self, value: {row['rust_type']}) -> Self {{",
                f"        self.with(StyleProperty::{row['rust_name']}, value)",
                "    }",
            )
        )
        for row in schema
    )
    text = f"""// @generated by tools/style/generate_properties.py; do not edit.

/// Stable property identifiers shared by Rust and the v0.2 C ABI.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StyleProperty {{
{variants}
}}

impl StyleProperty {{
    pub fn from_u16(value: u16) -> Option<Self> {{
        PROPERTY_METADATA
            .get(value.checked_sub(1)? as usize)
            .map(|metadata| metadata.property)
    }}

    /// Look up a schema property. This is intended for tooling and macro expansion;
    /// application mutation APIs accept `StyleProperty`, never a runtime name.
    pub fn from_css_name(name: &str) -> Option<Self> {{
        match name {{
{lookups}
            _ => None,
        }}
    }}

    pub fn metadata(self) -> &'static PropertyMetadata {{
        &PROPERTY_METADATA[self as usize - 1]
    }}
}}

pub const PROPERTY_METADATA: &[PropertyMetadata] = &[
{metadata}
];

#[rustfmt::skip]
impl Style {{
{builders}
}}
"""
    return text.encode()


def c_output(schema: list[dict[str, str]]) -> bytes:
    enum_rows = "\n".join(
        f"  OUI_STYLE_PROPERTY_{screaming(row['css_name'])} = {row['id']}," for row in schema
    )
    text = f"""/* @generated by tools/style/generate_properties.py; do not edit. */
#ifndef OPENUI_STYLE_PROPERTIES_H_
#define OPENUI_STYLE_PROPERTIES_H_

#include <stdint.h>

#define OUI_STYLE_SCHEMA_VERSION 2u

typedef enum OuiStyleProperty {{
{enum_rows}
}} OuiStyleProperty;

typedef enum OuiStyleValueTag {{
  OUI_STYLE_VALUE_LENGTH = 1,
  OUI_STYLE_VALUE_NUMBER = 2,
  OUI_STYLE_VALUE_INTEGER = 3,
  OUI_STYLE_VALUE_COLOR = 4,
  OUI_STYLE_VALUE_ENUM = 5,
  OUI_STYLE_VALUE_COMPOUND = 6
}} OuiStyleValueTag;

#endif  /* OPENUI_STYLE_PROPERTIES_H_ */
"""
    return text.encode()


def framework_output(schema: list[dict[str, str]]) -> bytes:
    setters = "\n".join(
        "\n".join(
            (
                f"    pub fn set_{rust_method(row['css_name'])}(&self, value: {row['rust_type']}) -> Result<(), Error> {{",
                f"        self.set_property(StyleProperty::{row['rust_name']}, value.into())",
                "    }",
            )
        )
        for row in schema
    )
    text = f"""// @generated by tools/style/generate_properties.py; do not edit.

use crate::style::Error;
use crate::typed_style::*;
use crate::Element;

#[rustfmt::skip]
impl Element {{
{setters}
}}
"""
    return text.encode()


def docs_output(schema: list[dict[str, str]]) -> bytes:
    lines = [
        "<!-- @generated by tools/style/generate_properties.py; do not edit. -->",
        "# Open UI v0.2 style properties",
        "",
        "| ID | Property | Rust type | Initial | Inherited | Invalidation | Interpolation |",
        "|---:|---|---|---|:---:|---|---|",
    ]
    lines.extend(
        f"| {row['id']} | `{row['css_name']}` | `{row['rust_type']}` | `{row['initial']}` | "
        f"{row['inherited']} | {row['invalidation']} | {row['interpolation']} |"
        for row in schema
    )
    return ("\n".join(lines) + "\n").encode()


def outputs() -> dict[Path, bytes]:
    schema = rows()
    return {
        RUST_OUT: rust_output(schema),
        FRAMEWORK_OUT: framework_output(schema),
        C_OUT: c_output(schema),
        DOC_OUT: docs_output(schema),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = outputs()
    if args.check:
        drift = [str(path.relative_to(ROOT)) for path, data in generated.items() if not path.is_file() or path.read_bytes() != data]
        if drift:
            raise SystemExit("generated style schema drift: " + ", ".join(drift))
        print(f"style schema: properties={len(rows())} drift=0")
        return
    for path, data in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    print(f"style schema: wrote={len(generated)} properties={len(rows())}")


if __name__ == "__main__":
    main()
