//! WPT tests: css_display
//! Auto-generated by tools/wpt/port_wpt.py
//! DO NOT EDIT MANUALLY

use openui_dom::{Document, ElementTag, NodeId};
use openui_geometry::Length;
use openui_style::*;

use crate::base_doc;

// Source: display-contents-block-002-ref.html
fn css_display_display_contents_block_002_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.margin_top = Length::px(300.0);
    doc.append_child(vp, n1);
    doc
}

// Source: display-contents-dynamic-pseudo-insertion-001-ref.html
fn css_display_display_contents_dynamic_pseudo_insertion_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Span);
    doc.append_child(vp, n1);
    doc
}

// Source: display-contents-flex-001-ref.html
fn css_display_display_contents_flex_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Inline;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n3, n4);
    doc
}

// Source: display-contents-flex-002-ref.html
fn css_display_display_contents_flex_002_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n2, n4);
                let n5 = doc.create_node(ElementTag::Div);
                doc.node_mut(n5).style.display = Display::Block;
                doc.append_child(n4, n5);
            let n6 = doc.create_node(ElementTag::Div);
            doc.node_mut(n6).style.display = Display::Block;
            doc.append_child(n2, n6);
                let n7 = doc.create_node(ElementTag::Div);
                doc.node_mut(n7).style.display = Display::Block;
                doc.append_child(n6, n7);
                    let n8 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n8).style.display = Display::Block;
                    doc.append_child(n7, n8);
                        let n9 = doc.create_node(ElementTag::Span);
                        doc.append_child(n8, n9);
            let n10 = doc.create_node(ElementTag::Div);
            doc.node_mut(n10).style.display = Display::Block;
            doc.append_child(n2, n10);
                let n11 = doc.create_node(ElementTag::Div);
                doc.node_mut(n11).style.display = Display::Block;
                doc.append_child(n10, n11);
                    let n12 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n12).style.display = Display::Block;
                    doc.append_child(n11, n12);
                        let n13 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n13).style.display = Display::Block;
                        doc.append_child(n12, n13);
                            let n14 = doc.create_node(ElementTag::Span);
                            doc.append_child(n13, n14);
            let n15 = doc.create_node(ElementTag::Div);
            doc.node_mut(n15).style.display = Display::Block;
            doc.append_child(n2, n15);
            let n16 = doc.create_node(ElementTag::Div);
            doc.node_mut(n16).style.display = Display::Block;
            doc.append_child(n2, n16);
                let n17 = doc.create_node(ElementTag::Div);
                doc.node_mut(n17).style.display = Display::Block;
                doc.append_child(n16, n17);
            let n18 = doc.create_node(ElementTag::Div);
            doc.node_mut(n18).style.display = Display::Block;
            doc.append_child(n2, n18);
                let n19 = doc.create_node(ElementTag::Div);
                doc.node_mut(n19).style.display = Display::Block;
                doc.append_child(n18, n19);
            let n20 = doc.create_node(ElementTag::Div);
            doc.node_mut(n20).style.display = Display::Block;
            doc.append_child(n2, n20);
            let n21 = doc.create_node(ElementTag::Div);
            doc.node_mut(n21).style.display = Display::Block;
            doc.append_child(n2, n21);
                let n22 = doc.create_node(ElementTag::Div);
                doc.node_mut(n22).style.display = Display::Block;
                doc.append_child(n21, n22);
            let n23 = doc.create_node(ElementTag::Div);
            doc.node_mut(n23).style.display = Display::Block;
            doc.append_child(n2, n23);
                let n24 = doc.create_node(ElementTag::Div);
                doc.node_mut(n24).style.display = Display::Block;
                doc.append_child(n23, n24);
                    let n25 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n25).style.display = Display::Block;
                    doc.append_child(n24, n25);
                        let n26 = doc.create_node(ElementTag::Span);
                        doc.append_child(n25, n26);
            let n27 = doc.create_node(ElementTag::Div);
            doc.node_mut(n27).style.display = Display::Block;
            doc.append_child(n2, n27);
                let n28 = doc.create_node(ElementTag::Div);
                doc.node_mut(n28).style.display = Display::Block;
                doc.append_child(n27, n28);
            let n29 = doc.create_node(ElementTag::Div);
            doc.node_mut(n29).style.display = Display::Block;
            doc.append_child(n2, n29);
                let n30 = doc.create_node(ElementTag::Div);
                doc.node_mut(n30).style.display = Display::Block;
                doc.append_child(n29, n30);
                    let n31 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n31).style.display = Display::Block;
                    doc.append_child(n30, n31);
            let n32 = doc.create_node(ElementTag::Span);
            doc.append_child(n2, n32);
            let n33 = doc.create_node(ElementTag::Div);
            doc.node_mut(n33).style.display = Display::Block;
            doc.append_child(n2, n33);
            let n34 = doc.create_node(ElementTag::Div);
            doc.node_mut(n34).style.display = Display::Block;
            doc.append_child(n2, n34);
                let n35 = doc.create_node(ElementTag::Div);
                doc.node_mut(n35).style.display = Display::Block;
                doc.append_child(n34, n35);
    doc
}

// Source: display-contents-flex-002.html
fn css_display_display_contents_flex_002() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n3, n4);
        let n5 = doc.create_node(ElementTag::Div);
        doc.node_mut(n5).style.display = Display::Block;
        doc.append_child(n1, n5);
            let n6 = doc.create_node(ElementTag::Div);
            doc.node_mut(n6).style.display = Display::Block;
            doc.append_child(n5, n6);
                let n7 = doc.create_node(ElementTag::Div);
                doc.node_mut(n7).style.display = Display::Block;
                doc.append_child(n6, n7);
                    let n8 = doc.create_node(ElementTag::Span);
                    doc.append_child(n7, n8);
        let n9 = doc.create_node(ElementTag::Div);
        doc.node_mut(n9).style.display = Display::Block;
        doc.append_child(n1, n9);
            let n10 = doc.create_node(ElementTag::Div);
            doc.node_mut(n10).style.display = Display::Block;
            doc.append_child(n9, n10);
                let n11 = doc.create_node(ElementTag::Div);
                doc.node_mut(n11).style.display = Display::Block;
                doc.append_child(n10, n11);
                    let n12 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n12).style.display = Display::Block;
                    doc.append_child(n11, n12);
                        let n13 = doc.create_node(ElementTag::Span);
                        doc.append_child(n12, n13);
        let n14 = doc.create_node(ElementTag::Div);
        doc.node_mut(n14).style.display = Display::Block;
        doc.append_child(n1, n14);
            let n15 = doc.create_node(ElementTag::Div);
            doc.node_mut(n15).style.display = Display::Block;
            doc.append_child(n14, n15);
        let n16 = doc.create_node(ElementTag::Div);
        doc.node_mut(n16).style.display = Display::Block;
        doc.append_child(n1, n16);
            let n17 = doc.create_node(ElementTag::Div);
            doc.node_mut(n17).style.display = Display::Block;
            doc.append_child(n16, n17);
        let n18 = doc.create_node(ElementTag::Div);
        doc.node_mut(n18).style.display = Display::Block;
        doc.append_child(n1, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n18, n19);
        let n20 = doc.create_node(ElementTag::Div);
        doc.node_mut(n20).style.display = Display::Block;
        doc.append_child(n1, n20);
        let n21 = doc.create_node(ElementTag::Div);
        doc.node_mut(n21).style.display = Display::Block;
        doc.append_child(n1, n21);
            let n22 = doc.create_node(ElementTag::Div);
            doc.node_mut(n22).style.display = Display::Block;
            doc.append_child(n21, n22);
        let n23 = doc.create_node(ElementTag::Div);
        doc.node_mut(n23).style.display = Display::Block;
        doc.append_child(n1, n23);
            let n24 = doc.create_node(ElementTag::Div);
            doc.node_mut(n24).style.display = Display::Block;
            doc.append_child(n23, n24);
                let n25 = doc.create_node(ElementTag::Div);
                doc.node_mut(n25).style.display = Display::Block;
                doc.append_child(n24, n25);
                    let n26 = doc.create_node(ElementTag::Span);
                    doc.append_child(n25, n26);
        let n27 = doc.create_node(ElementTag::Div);
        doc.node_mut(n27).style.display = Display::Block;
        doc.append_child(n1, n27);
            let n28 = doc.create_node(ElementTag::Div);
            doc.node_mut(n28).style.display = Display::Block;
            doc.append_child(n27, n28);
        let n29 = doc.create_node(ElementTag::Div);
        doc.node_mut(n29).style.display = Display::Block;
        doc.append_child(n1, n29);
            let n30 = doc.create_node(ElementTag::Div);
            doc.node_mut(n30).style.display = Display::Block;
            doc.append_child(n29, n30);
                let n31 = doc.create_node(ElementTag::Div);
                doc.node_mut(n31).style.display = Display::Block;
                doc.append_child(n30, n31);
                    let n32 = doc.create_node(ElementTag::Span);
                    doc.append_child(n31, n32);
        let n33 = doc.create_node(ElementTag::Div);
        doc.node_mut(n33).style.display = Display::Block;
        doc.append_child(n1, n33);
            let n34 = doc.create_node(ElementTag::Div);
            doc.node_mut(n34).style.display = Display::Block;
            doc.append_child(n33, n34);
    doc
}

// Source: display-contents-flex-003.html
fn css_display_display_contents_flex_003() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n2, n4);
                let n5 = doc.create_node(ElementTag::Div);
                doc.node_mut(n5).style.display = Display::Block;
                doc.append_child(n4, n5);
            let n6 = doc.create_node(ElementTag::Div);
            doc.node_mut(n6).style.display = Display::Block;
            doc.append_child(n2, n6);
                let n7 = doc.create_node(ElementTag::Div);
                doc.node_mut(n7).style.display = Display::Block;
                doc.append_child(n6, n7);
                    let n8 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n8).style.display = Display::Block;
                    doc.append_child(n7, n8);
                        let n9 = doc.create_node(ElementTag::Span);
                        doc.append_child(n8, n9);
            let n10 = doc.create_node(ElementTag::Div);
            doc.node_mut(n10).style.display = Display::Block;
            doc.append_child(n2, n10);
                let n11 = doc.create_node(ElementTag::Div);
                doc.node_mut(n11).style.display = Display::Block;
                doc.append_child(n10, n11);
                    let n12 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n12).style.display = Display::Block;
                    doc.append_child(n11, n12);
                        let n13 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n13).style.display = Display::Block;
                        doc.append_child(n12, n13);
                            let n14 = doc.create_node(ElementTag::Span);
                            doc.append_child(n13, n14);
            let n15 = doc.create_node(ElementTag::Div);
            doc.node_mut(n15).style.display = Display::Block;
            doc.append_child(n2, n15);
                let n16 = doc.create_node(ElementTag::Div);
                doc.node_mut(n16).style.display = Display::Block;
                doc.append_child(n15, n16);
            let n17 = doc.create_node(ElementTag::Div);
            doc.node_mut(n17).style.display = Display::Block;
            doc.append_child(n2, n17);
                let n18 = doc.create_node(ElementTag::Div);
                doc.node_mut(n18).style.display = Display::Block;
                doc.append_child(n17, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n2, n19);
                let n20 = doc.create_node(ElementTag::Div);
                doc.node_mut(n20).style.display = Display::Block;
                doc.append_child(n19, n20);
            let n21 = doc.create_node(ElementTag::Div);
            doc.node_mut(n21).style.display = Display::Block;
            doc.append_child(n2, n21);
            let n22 = doc.create_node(ElementTag::Div);
            doc.node_mut(n22).style.display = Display::Block;
            doc.append_child(n2, n22);
                let n23 = doc.create_node(ElementTag::Div);
                doc.node_mut(n23).style.display = Display::Block;
                doc.append_child(n22, n23);
            let n24 = doc.create_node(ElementTag::Div);
            doc.node_mut(n24).style.display = Display::Block;
            doc.append_child(n2, n24);
                let n25 = doc.create_node(ElementTag::Div);
                doc.node_mut(n25).style.display = Display::Block;
                doc.append_child(n24, n25);
                    let n26 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n26).style.display = Display::Block;
                    doc.append_child(n25, n26);
                        let n27 = doc.create_node(ElementTag::Span);
                        doc.append_child(n26, n27);
            let n28 = doc.create_node(ElementTag::Div);
            doc.node_mut(n28).style.display = Display::Block;
            doc.append_child(n2, n28);
                let n29 = doc.create_node(ElementTag::Div);
                doc.node_mut(n29).style.display = Display::Block;
                doc.append_child(n28, n29);
            let n30 = doc.create_node(ElementTag::Div);
            doc.node_mut(n30).style.display = Display::Block;
            doc.append_child(n2, n30);
                let n31 = doc.create_node(ElementTag::Div);
                doc.node_mut(n31).style.display = Display::Block;
                doc.append_child(n30, n31);
                    let n32 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n32).style.display = Display::Block;
                    doc.append_child(n31, n32);
                        let n33 = doc.create_node(ElementTag::Span);
                        doc.append_child(n32, n33);
            let n34 = doc.create_node(ElementTag::Div);
            doc.node_mut(n34).style.display = Display::Block;
            doc.append_child(n2, n34);
                let n35 = doc.create_node(ElementTag::Div);
                doc.node_mut(n35).style.display = Display::Block;
                doc.append_child(n34, n35);
    doc
}

// Source: display-contents-inline-flex-001-ref.html
fn css_display_display_contents_inline_flex_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.append_child(n1, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.append_child(n4, n5);
                let n6 = doc.create_node(ElementTag::Div);
                doc.node_mut(n6).style.display = Display::Block;
                doc.append_child(n5, n6);
        let n7 = doc.create_node(ElementTag::Div);
        doc.node_mut(n7).style.display = Display::Block;
        doc.append_child(n1, n7);
            let n8 = doc.create_node(ElementTag::Div);
            doc.node_mut(n8).style.display = Display::Block;
            doc.append_child(n7, n8);
                let n9 = doc.create_node(ElementTag::Div);
                doc.node_mut(n9).style.display = Display::Block;
                doc.append_child(n8, n9);
        let n10 = doc.create_node(ElementTag::Div);
        doc.node_mut(n10).style.display = Display::Block;
        doc.append_child(n1, n10);
            let n11 = doc.create_node(ElementTag::Div);
            doc.node_mut(n11).style.display = Display::Block;
            doc.append_child(n10, n11);
                let n12 = doc.create_node(ElementTag::Div);
                doc.node_mut(n12).style.display = Display::Block;
                doc.append_child(n11, n12);
        let n13 = doc.create_node(ElementTag::Div);
        doc.node_mut(n13).style.display = Display::Block;
        doc.append_child(n1, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.append_child(n13, n14);
            let n15 = doc.create_node(ElementTag::Div);
            doc.node_mut(n15).style.display = Display::Block;
            doc.append_child(n13, n15);
                let n16 = doc.create_node(ElementTag::Div);
                doc.node_mut(n16).style.display = Display::Block;
                doc.append_child(n15, n16);
            let n17 = doc.create_node(ElementTag::Div);
            doc.node_mut(n17).style.display = Display::Block;
            doc.append_child(n13, n17);
        let n18 = doc.create_node(ElementTag::Div);
        doc.node_mut(n18).style.display = Display::Block;
        doc.append_child(n1, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n18, n19);
            let n20 = doc.create_node(ElementTag::Div);
            doc.node_mut(n20).style.display = Display::Block;
            doc.append_child(n18, n20);
                let n21 = doc.create_node(ElementTag::Div);
                doc.node_mut(n21).style.display = Display::Block;
                doc.append_child(n20, n21);
            let n22 = doc.create_node(ElementTag::Div);
            doc.node_mut(n22).style.display = Display::Block;
            doc.append_child(n18, n22);
    doc
}

// Source: display-contents-inline-flex-001.html
fn css_display_display_contents_inline_flex_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.append_child(n1, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.append_child(n4, n5);
                let n6 = doc.create_node(ElementTag::Div);
                doc.node_mut(n6).style.display = Display::Block;
                doc.append_child(n5, n6);
        let n7 = doc.create_node(ElementTag::Div);
        doc.node_mut(n7).style.display = Display::Block;
        doc.append_child(n1, n7);
            let n8 = doc.create_node(ElementTag::Div);
            doc.node_mut(n8).style.display = Display::Block;
            doc.append_child(n7, n8);
                let n9 = doc.create_node(ElementTag::Div);
                doc.node_mut(n9).style.display = Display::Block;
                doc.append_child(n8, n9);
        let n10 = doc.create_node(ElementTag::Div);
        doc.node_mut(n10).style.display = Display::Block;
        doc.append_child(n1, n10);
            let n11 = doc.create_node(ElementTag::Div);
            doc.node_mut(n11).style.display = Display::Block;
            doc.append_child(n10, n11);
                let n12 = doc.create_node(ElementTag::Div);
                doc.node_mut(n12).style.display = Display::Block;
                doc.append_child(n11, n12);
        let n13 = doc.create_node(ElementTag::Div);
        doc.node_mut(n13).style.display = Display::Block;
        doc.append_child(n1, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.append_child(n13, n14);
            let n15 = doc.create_node(ElementTag::Div);
            doc.node_mut(n15).style.display = Display::Block;
            doc.append_child(n13, n15);
                let n16 = doc.create_node(ElementTag::Div);
                doc.node_mut(n16).style.display = Display::Block;
                doc.append_child(n15, n16);
            let n17 = doc.create_node(ElementTag::Div);
            doc.node_mut(n17).style.display = Display::Block;
            doc.append_child(n13, n17);
        let n18 = doc.create_node(ElementTag::Div);
        doc.node_mut(n18).style.display = Display::Block;
        doc.append_child(n1, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n18, n19);
            let n20 = doc.create_node(ElementTag::Div);
            doc.node_mut(n20).style.display = Display::Block;
            doc.append_child(n18, n20);
                let n21 = doc.create_node(ElementTag::Div);
                doc.node_mut(n21).style.display = Display::Block;
                doc.append_child(n20, n21);
            let n22 = doc.create_node(ElementTag::Div);
            doc.node_mut(n22).style.display = Display::Block;
            doc.append_child(n18, n22);
    doc
}

// Source: display-contents-list-001-ref.html
fn css_display_display_contents_list_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n5).style.display = Display::Block;
                    doc.append_child(n4, n5);
                    let n6 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n6).style.display = Display::Block;
                    doc.append_child(n4, n6);
                        let n7 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n7).style.display = Display::Block;
                        doc.append_child(n6, n7);
                    let n8 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n8).style.display = Display::Block;
                    doc.append_child(n4, n8);
                        let n9 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n9).style.display = Display::Block;
                        doc.append_child(n8, n9);
                            let n10 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n10).style.display = Display::Block;
                            doc.append_child(n9, n10);
                                let n11 = doc.create_node(ElementTag::Span);
                                doc.append_child(n10, n11);
                    let n12 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n12).style.display = Display::Block;
                    doc.append_child(n4, n12);
                        let n13 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n13).style.display = Display::Block;
                        doc.append_child(n12, n13);
                            let n14 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n14).style.display = Display::Block;
                            doc.append_child(n13, n14);
                                let n15 = doc.create_node(ElementTag::Div);
                                doc.node_mut(n15).style.display = Display::Block;
                                doc.append_child(n14, n15);
                                    let n16 = doc.create_node(ElementTag::Span);
                                    doc.append_child(n15, n16);
                    let n17 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n17).style.display = Display::Block;
                    doc.append_child(n4, n17);
                        let n18 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n18).style.display = Display::Block;
                        doc.append_child(n17, n18);
                    let n19 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n19).style.display = Display::Block;
                    doc.append_child(n4, n19);
                        let n20 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n20).style.display = Display::Block;
                        doc.append_child(n19, n20);
                    let n21 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n21).style.display = Display::Block;
                    doc.append_child(n4, n21);
                        let n22 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n22).style.display = Display::Block;
                        doc.append_child(n21, n22);
                    let n23 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n23).style.display = Display::Block;
                    doc.append_child(n4, n23);
                    let n24 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n24).style.display = Display::Block;
                    doc.append_child(n4, n24);
                        let n25 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n25).style.display = Display::Block;
                        doc.append_child(n24, n25);
                    let n26 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n26).style.display = Display::Block;
                    doc.append_child(n4, n26);
                        let n27 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n27).style.display = Display::Block;
                        doc.append_child(n26, n27);
                            let n28 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n28).style.display = Display::Block;
                            doc.append_child(n27, n28);
                                let n29 = doc.create_node(ElementTag::Span);
                                doc.append_child(n28, n29);
                    let n30 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n30).style.display = Display::Block;
                    doc.append_child(n4, n30);
                        let n31 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n31).style.display = Display::Block;
                        doc.append_child(n30, n31);
                    let n32 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n32).style.display = Display::Block;
                    doc.append_child(n4, n32);
                        let n33 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n33).style.display = Display::Block;
                        doc.append_child(n32, n33);
                            let n34 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n34).style.display = Display::Block;
                            doc.append_child(n33, n34);
                                let n35 = doc.create_node(ElementTag::Span);
                                doc.append_child(n34, n35);
                    let n36 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n36).style.display = Display::Block;
                    doc.append_child(n4, n36);
                        let n37 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n37).style.display = Display::Block;
                        doc.append_child(n36, n37);
    doc
}

// Source: display-contents-list-001.html
fn css_display_display_contents_list_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n5).style.display = Display::Block;
                    doc.append_child(n4, n5);
                    let n6 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n6).style.display = Display::Block;
                    doc.append_child(n4, n6);
                        let n7 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n7).style.display = Display::Block;
                        doc.append_child(n6, n7);
                    let n8 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n8).style.display = Display::Block;
                    doc.append_child(n4, n8);
                        let n9 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n9).style.display = Display::Block;
                        doc.append_child(n8, n9);
                            let n10 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n10).style.display = Display::Block;
                            doc.append_child(n9, n10);
                                let n11 = doc.create_node(ElementTag::Span);
                                doc.append_child(n10, n11);
                    let n12 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n12).style.display = Display::Block;
                    doc.append_child(n4, n12);
                        let n13 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n13).style.display = Display::Block;
                        doc.append_child(n12, n13);
                            let n14 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n14).style.display = Display::Block;
                            doc.append_child(n13, n14);
                                let n15 = doc.create_node(ElementTag::Div);
                                doc.node_mut(n15).style.display = Display::Block;
                                doc.append_child(n14, n15);
                                    let n16 = doc.create_node(ElementTag::Span);
                                    doc.append_child(n15, n16);
                    let n17 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n17).style.display = Display::Block;
                    doc.append_child(n4, n17);
                        let n18 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n18).style.display = Display::Block;
                        doc.append_child(n17, n18);
                    let n19 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n19).style.display = Display::Block;
                    doc.append_child(n4, n19);
                        let n20 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n20).style.display = Display::Block;
                        doc.append_child(n19, n20);
                    let n21 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n21).style.display = Display::Block;
                    doc.append_child(n4, n21);
                        let n22 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n22).style.display = Display::Block;
                        doc.append_child(n21, n22);
                    let n23 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n23).style.display = Display::Block;
                    doc.append_child(n4, n23);
                    let n24 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n24).style.display = Display::Block;
                    doc.append_child(n4, n24);
                        let n25 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n25).style.display = Display::Block;
                        doc.append_child(n24, n25);
                    let n26 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n26).style.display = Display::Block;
                    doc.append_child(n4, n26);
                        let n27 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n27).style.display = Display::Block;
                        doc.append_child(n26, n27);
                            let n28 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n28).style.display = Display::Block;
                            doc.append_child(n27, n28);
                                let n29 = doc.create_node(ElementTag::Span);
                                doc.append_child(n28, n29);
                    let n30 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n30).style.display = Display::Block;
                    doc.append_child(n4, n30);
                        let n31 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n31).style.display = Display::Block;
                        doc.append_child(n30, n31);
                    let n32 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n32).style.display = Display::Block;
                    doc.append_child(n4, n32);
                        let n33 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n33).style.display = Display::Block;
                        doc.append_child(n32, n33);
                            let n34 = doc.create_node(ElementTag::Div);
                            doc.node_mut(n34).style.display = Display::Block;
                            doc.append_child(n33, n34);
                                let n35 = doc.create_node(ElementTag::Span);
                                doc.append_child(n34, n35);
                    let n36 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n36).style.display = Display::Block;
                    doc.append_child(n4, n36);
                        let n37 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n37).style.display = Display::Block;
                        doc.append_child(n36, n37);
    doc
}

// Source: display-contents-multicol-001-ref.html
fn css_display_display_contents_multicol_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n5).style.display = Display::Block;
                    doc.append_child(n4, n5);
                        let n6 = doc.create_node(ElementTag::Span);
                        doc.append_child(n5, n6);
            let n7 = doc.create_node(ElementTag::Div);
            doc.node_mut(n7).style.display = Display::Block;
            doc.append_child(n2, n7);
                let n8 = doc.create_node(ElementTag::Div);
                doc.node_mut(n8).style.display = Display::Block;
                doc.append_child(n7, n8);
            let n9 = doc.create_node(ElementTag::Div);
            doc.node_mut(n9).style.display = Display::Block;
            doc.append_child(n2, n9);
                let n10 = doc.create_node(ElementTag::Div);
                doc.node_mut(n10).style.display = Display::Block;
                doc.append_child(n9, n10);
        let n11 = doc.create_node(ElementTag::Div);
        doc.node_mut(n11).style.display = Display::Block;
        doc.append_child(n1, n11);
            let n12 = doc.create_node(ElementTag::Div);
            doc.node_mut(n12).style.display = Display::Block;
            doc.append_child(n11, n12);
                let n13 = doc.create_node(ElementTag::Div);
                doc.node_mut(n13).style.display = Display::Block;
                doc.append_child(n12, n13);
                    let n14 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n14).style.display = Display::Block;
                    doc.append_child(n13, n14);
                        let n15 = doc.create_node(ElementTag::Span);
                        doc.append_child(n14, n15);
            let n16 = doc.create_node(ElementTag::Div);
            doc.node_mut(n16).style.display = Display::Block;
            doc.append_child(n11, n16);
                let n17 = doc.create_node(ElementTag::Div);
                doc.node_mut(n17).style.display = Display::Block;
                doc.append_child(n16, n17);
            let n18 = doc.create_node(ElementTag::Div);
            doc.node_mut(n18).style.display = Display::Block;
            doc.append_child(n11, n18);
                let n19 = doc.create_node(ElementTag::Div);
                doc.node_mut(n19).style.display = Display::Block;
                doc.append_child(n18, n19);
    doc
}

// Source: display-contents-multicol-001.html
fn css_display_display_contents_multicol_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n5).style.display = Display::Block;
                    doc.append_child(n4, n5);
                        let n6 = doc.create_node(ElementTag::Span);
                        doc.append_child(n5, n6);
            let n7 = doc.create_node(ElementTag::Div);
            doc.node_mut(n7).style.display = Display::Block;
            doc.append_child(n2, n7);
                let n8 = doc.create_node(ElementTag::Div);
                doc.node_mut(n8).style.display = Display::Block;
                doc.append_child(n7, n8);
            let n9 = doc.create_node(ElementTag::Div);
            doc.node_mut(n9).style.display = Display::Block;
            doc.append_child(n2, n9);
                let n10 = doc.create_node(ElementTag::Div);
                doc.node_mut(n10).style.display = Display::Block;
                doc.append_child(n9, n10);
        let n11 = doc.create_node(ElementTag::Div);
        doc.node_mut(n11).style.display = Display::Block;
        doc.append_child(n1, n11);
            let n12 = doc.create_node(ElementTag::Div);
            doc.node_mut(n12).style.display = Display::Block;
            doc.append_child(n11, n12);
                let n13 = doc.create_node(ElementTag::Div);
                doc.node_mut(n13).style.display = Display::Block;
                doc.append_child(n12, n13);
                    let n14 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n14).style.display = Display::Block;
                    doc.append_child(n13, n14);
                        let n15 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n15).style.display = Display::Block;
                        doc.append_child(n14, n15);
                            let n16 = doc.create_node(ElementTag::Span);
                            doc.append_child(n15, n16);
                let n17 = doc.create_node(ElementTag::Div);
                doc.node_mut(n17).style.display = Display::Block;
                doc.append_child(n12, n17);
                    let n18 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n18).style.display = Display::Block;
                    doc.append_child(n17, n18);
                let n19 = doc.create_node(ElementTag::Div);
                doc.node_mut(n19).style.display = Display::Block;
                doc.append_child(n12, n19);
                    let n20 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n20).style.display = Display::Block;
                    doc.append_child(n19, n20);
    doc
}

// Source: display-contents-pass-green-no-red-ref.html
fn css_display_display_contents_pass_green_no_red_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Span);
        doc.append_child(n1, n2);
    doc
}

// Source: display-contents-pass-no-red-ref.html
fn css_display_display_contents_pass_no_red_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Span);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Span);
        doc.append_child(n1, n3);
    doc
}

// Source: display-contents-pass-ref.html
fn css_display_display_contents_pass_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc
}

// Source: display-contents-root-background-ref.html
fn css_display_display_contents_root_background_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc
}

// Source: display-contents-state-change-001-ref.html
fn css_display_display_contents_state_change_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    doc
}

// Source: display-contents-table-001-ref.html
fn css_display_display_contents_table_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Span);
            doc.append_child(n2, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.append_child(n1, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.append_child(n4, n5);
                let n6 = doc.create_node(ElementTag::Div);
                doc.node_mut(n6).style.display = Display::Block;
                doc.append_child(n5, n6);
                    let n7 = doc.create_node(ElementTag::Span);
                    doc.append_child(n6, n7);
        let n8 = doc.create_node(ElementTag::Div);
        doc.node_mut(n8).style.display = Display::Block;
        doc.append_child(n1, n8);
        let n9 = doc.create_node(ElementTag::Div);
        doc.node_mut(n9).style.display = Display::Block;
        doc.append_child(n1, n9);
        let n10 = doc.create_node(ElementTag::Div);
        doc.node_mut(n10).style.display = Display::Block;
        doc.append_child(n1, n10);
        let n11 = doc.create_node(ElementTag::Div);
        doc.node_mut(n11).style.display = Display::Block;
        doc.append_child(n1, n11);
        let n12 = doc.create_node(ElementTag::Div);
        doc.node_mut(n12).style.display = Display::Block;
        doc.append_child(n1, n12);
        let n13 = doc.create_node(ElementTag::Div);
        doc.node_mut(n13).style.display = Display::Block;
        doc.append_child(n1, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.append_child(n13, n14);
                let n15 = doc.create_node(ElementTag::Span);
                doc.append_child(n14, n15);
        let n16 = doc.create_node(ElementTag::Div);
        doc.node_mut(n16).style.display = Display::Block;
        doc.append_child(n1, n16);
        let n17 = doc.create_node(ElementTag::Div);
        doc.node_mut(n17).style.display = Display::Block;
        doc.append_child(n1, n17);
        let n18 = doc.create_node(ElementTag::Div);
        doc.node_mut(n18).style.display = Display::Block;
        doc.append_child(n1, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n18, n19);
                let n20 = doc.create_node(ElementTag::Span);
                doc.append_child(n19, n20);
        let n21 = doc.create_node(ElementTag::Div);
        doc.node_mut(n21).style.display = Display::Block;
        doc.append_child(n1, n21);
    doc
}

// Source: display-contents-table-001.html
fn css_display_display_contents_table_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Span);
                    doc.append_child(n4, n5);
        let n6 = doc.create_node(ElementTag::Div);
        doc.node_mut(n6).style.display = Display::Block;
        doc.append_child(n1, n6);
            let n7 = doc.create_node(ElementTag::Div);
            doc.node_mut(n7).style.display = Display::Block;
            doc.append_child(n6, n7);
                let n8 = doc.create_node(ElementTag::Div);
                doc.node_mut(n8).style.display = Display::Block;
                doc.append_child(n7, n8);
                    let n9 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n9).style.display = Display::Block;
                    doc.append_child(n8, n9);
                        let n10 = doc.create_node(ElementTag::Span);
                        doc.append_child(n9, n10);
        let n11 = doc.create_node(ElementTag::Div);
        doc.node_mut(n11).style.display = Display::Block;
        doc.append_child(n1, n11);
            let n12 = doc.create_node(ElementTag::Div);
            doc.node_mut(n12).style.display = Display::Block;
            doc.append_child(n11, n12);
        let n13 = doc.create_node(ElementTag::Div);
        doc.node_mut(n13).style.display = Display::Block;
        doc.append_child(n1, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.append_child(n13, n14);
        let n15 = doc.create_node(ElementTag::Div);
        doc.node_mut(n15).style.display = Display::Block;
        doc.append_child(n1, n15);
            let n16 = doc.create_node(ElementTag::Div);
            doc.node_mut(n16).style.display = Display::Block;
            doc.append_child(n15, n16);
        let n17 = doc.create_node(ElementTag::Div);
        doc.node_mut(n17).style.display = Display::Block;
        doc.append_child(n1, n17);
        let n18 = doc.create_node(ElementTag::Div);
        doc.node_mut(n18).style.display = Display::Block;
        doc.append_child(n1, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n18, n19);
        let n20 = doc.create_node(ElementTag::Div);
        doc.node_mut(n20).style.display = Display::Block;
        doc.append_child(n1, n20);
            let n21 = doc.create_node(ElementTag::Div);
            doc.node_mut(n21).style.display = Display::Block;
            doc.append_child(n20, n21);
                let n22 = doc.create_node(ElementTag::Div);
                doc.node_mut(n22).style.display = Display::Block;
                doc.append_child(n21, n22);
                    let n23 = doc.create_node(ElementTag::Span);
                    doc.append_child(n22, n23);
        let n24 = doc.create_node(ElementTag::Div);
        doc.node_mut(n24).style.display = Display::Block;
        doc.append_child(n1, n24);
            let n25 = doc.create_node(ElementTag::Div);
            doc.node_mut(n25).style.display = Display::Block;
            doc.append_child(n24, n25);
        let n26 = doc.create_node(ElementTag::Div);
        doc.node_mut(n26).style.display = Display::Block;
        doc.append_child(n1, n26);
            let n27 = doc.create_node(ElementTag::Div);
            doc.node_mut(n27).style.display = Display::Block;
            doc.append_child(n26, n27);
        let n28 = doc.create_node(ElementTag::Div);
        doc.node_mut(n28).style.display = Display::Block;
        doc.append_child(n1, n28);
            let n29 = doc.create_node(ElementTag::Div);
            doc.node_mut(n29).style.display = Display::Block;
            doc.append_child(n28, n29);
                let n30 = doc.create_node(ElementTag::Div);
                doc.node_mut(n30).style.display = Display::Block;
                doc.append_child(n29, n30);
                    let n31 = doc.create_node(ElementTag::Span);
                    doc.append_child(n30, n31);
        let n32 = doc.create_node(ElementTag::Div);
        doc.node_mut(n32).style.display = Display::Block;
        doc.append_child(n1, n32);
            let n33 = doc.create_node(ElementTag::Div);
            doc.node_mut(n33).style.display = Display::Block;
            doc.append_child(n32, n33);
    doc
}

// Source: display-contents-table-002-ref.html
fn css_display_display_contents_table_002_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.float = Float::Right;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Span);
                doc.append_child(n3, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.append_child(n2, n5);
                let n6 = doc.create_node(ElementTag::Div);
                doc.node_mut(n6).style.display = Display::Block;
                doc.append_child(n5, n6);
                    let n7 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n7).style.display = Display::Block;
                    doc.append_child(n6, n7);
                        let n8 = doc.create_node(ElementTag::Span);
                        doc.append_child(n7, n8);
            let n9 = doc.create_node(ElementTag::Div);
            doc.node_mut(n9).style.display = Display::Block;
            doc.node_mut(n9).style.border_top_style = BorderStyle::None;
            doc.node_mut(n9).style.border_right_style = BorderStyle::None;
            doc.node_mut(n9).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n9).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n9);
            let n10 = doc.create_node(ElementTag::Div);
            doc.node_mut(n10).style.display = Display::Block;
            doc.append_child(n2, n10);
            let n11 = doc.create_node(ElementTag::Div);
            doc.node_mut(n11).style.display = Display::Block;
            doc.node_mut(n11).style.border_top_style = BorderStyle::None;
            doc.node_mut(n11).style.border_right_style = BorderStyle::None;
            doc.node_mut(n11).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n11).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n11);
            let n12 = doc.create_node(ElementTag::Div);
            doc.node_mut(n12).style.display = Display::Block;
            doc.append_child(n2, n12);
            let n13 = doc.create_node(ElementTag::Div);
            doc.node_mut(n13).style.display = Display::Block;
            doc.append_child(n2, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.node_mut(n14).style.border_top_style = BorderStyle::None;
            doc.node_mut(n14).style.border_right_style = BorderStyle::None;
            doc.node_mut(n14).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n14).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n14);
                let n15 = doc.create_node(ElementTag::Div);
                doc.node_mut(n15).style.display = Display::Block;
                doc.append_child(n14, n15);
                    let n16 = doc.create_node(ElementTag::Span);
                    doc.append_child(n15, n16);
            let n17 = doc.create_node(ElementTag::Div);
            doc.node_mut(n17).style.display = Display::Block;
            doc.node_mut(n17).style.border_top_style = BorderStyle::None;
            doc.node_mut(n17).style.border_right_style = BorderStyle::None;
            doc.node_mut(n17).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n17).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n17);
            let n18 = doc.create_node(ElementTag::Div);
            doc.node_mut(n18).style.display = Display::Block;
            doc.node_mut(n18).style.border_top_style = BorderStyle::None;
            doc.node_mut(n18).style.border_right_style = BorderStyle::None;
            doc.node_mut(n18).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n18).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n2, n19);
                let n20 = doc.create_node(ElementTag::Div);
                doc.node_mut(n20).style.display = Display::Block;
                doc.append_child(n19, n20);
                    let n21 = doc.create_node(ElementTag::Span);
                    doc.append_child(n20, n21);
            let n22 = doc.create_node(ElementTag::Div);
            doc.node_mut(n22).style.display = Display::Block;
            doc.node_mut(n22).style.border_top_style = BorderStyle::None;
            doc.node_mut(n22).style.border_right_style = BorderStyle::None;
            doc.node_mut(n22).style.border_bottom_style = BorderStyle::None;
            doc.node_mut(n22).style.border_left_style = BorderStyle::None;
            doc.append_child(n2, n22);
    doc
}

// Source: display-contents-table-002.html
fn css_display_display_contents_table_002() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.float = Float::Right;
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.append_child(n3, n4);
                    let n5 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n5).style.display = Display::Block;
                    doc.append_child(n4, n5);
                        let n6 = doc.create_node(ElementTag::Span);
                        doc.append_child(n5, n6);
            let n7 = doc.create_node(ElementTag::Div);
            doc.node_mut(n7).style.display = Display::Block;
            doc.append_child(n2, n7);
                let n8 = doc.create_node(ElementTag::Div);
                doc.node_mut(n8).style.display = Display::Block;
                doc.append_child(n7, n8);
                    let n9 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n9).style.display = Display::Block;
                    doc.append_child(n8, n9);
                        let n10 = doc.create_node(ElementTag::Div);
                        doc.node_mut(n10).style.display = Display::Block;
                        doc.append_child(n9, n10);
                            let n11 = doc.create_node(ElementTag::Span);
                            doc.append_child(n10, n11);
            let n12 = doc.create_node(ElementTag::Div);
            doc.node_mut(n12).style.display = Display::Block;
            doc.append_child(n2, n12);
                let n13 = doc.create_node(ElementTag::Div);
                doc.node_mut(n13).style.display = Display::Block;
                doc.append_child(n12, n13);
            let n14 = doc.create_node(ElementTag::Div);
            doc.node_mut(n14).style.display = Display::Block;
            doc.append_child(n2, n14);
                let n15 = doc.create_node(ElementTag::Div);
                doc.node_mut(n15).style.display = Display::Block;
                doc.append_child(n14, n15);
            let n16 = doc.create_node(ElementTag::Div);
            doc.node_mut(n16).style.display = Display::Block;
            doc.append_child(n2, n16);
                let n17 = doc.create_node(ElementTag::Div);
                doc.node_mut(n17).style.display = Display::Block;
                doc.append_child(n16, n17);
            let n18 = doc.create_node(ElementTag::Div);
            doc.node_mut(n18).style.display = Display::Block;
            doc.append_child(n2, n18);
            let n19 = doc.create_node(ElementTag::Div);
            doc.node_mut(n19).style.display = Display::Block;
            doc.append_child(n2, n19);
                let n20 = doc.create_node(ElementTag::Div);
                doc.node_mut(n20).style.display = Display::Block;
                doc.append_child(n19, n20);
            let n21 = doc.create_node(ElementTag::Div);
            doc.node_mut(n21).style.display = Display::Block;
            doc.append_child(n2, n21);
                let n22 = doc.create_node(ElementTag::Div);
                doc.node_mut(n22).style.display = Display::Block;
                doc.append_child(n21, n22);
                    let n23 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n23).style.display = Display::Block;
                    doc.append_child(n22, n23);
                        let n24 = doc.create_node(ElementTag::Span);
                        doc.append_child(n23, n24);
            let n25 = doc.create_node(ElementTag::Div);
            doc.node_mut(n25).style.display = Display::Block;
            doc.append_child(n2, n25);
                let n26 = doc.create_node(ElementTag::Div);
                doc.node_mut(n26).style.display = Display::Block;
                doc.append_child(n25, n26);
            let n27 = doc.create_node(ElementTag::Div);
            doc.node_mut(n27).style.display = Display::Block;
            doc.append_child(n2, n27);
                let n28 = doc.create_node(ElementTag::Div);
                doc.node_mut(n28).style.display = Display::Block;
                doc.append_child(n27, n28);
            let n29 = doc.create_node(ElementTag::Div);
            doc.node_mut(n29).style.display = Display::Block;
            doc.append_child(n2, n29);
                let n30 = doc.create_node(ElementTag::Div);
                doc.node_mut(n30).style.display = Display::Block;
                doc.append_child(n29, n30);
                    let n31 = doc.create_node(ElementTag::Div);
                    doc.node_mut(n31).style.display = Display::Block;
                    doc.append_child(n30, n31);
                        let n32 = doc.create_node(ElementTag::Span);
                        doc.append_child(n31, n32);
            let n33 = doc.create_node(ElementTag::Div);
            doc.node_mut(n33).style.display = Display::Block;
            doc.append_child(n2, n33);
                let n34 = doc.create_node(ElementTag::Div);
                doc.node_mut(n34).style.display = Display::Block;
                doc.append_child(n33, n34);
    doc
}

// Source: display-contents-text-inherit-ref.html
fn css_display_display_contents_text_inherit_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc
}

// Source: display-contents-whitespace-inside-inline-ref.html
fn css_display_display_contents_whitespace_inside_inline_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Span);
    doc.append_child(vp, n1);
    doc
}

// Source: display-first-line-002-ref.html
fn css_display_display_first_line_002_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.color = Color::BLUE;
    doc.append_child(vp, n2);
    doc
}

// Source: display-flow-root-dynamic-ref.html
fn css_display_display_flow_root_dynamic_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.append_child(vp, n1);
    doc
}

pub fn css_display_registry() -> Vec<(&'static str, fn() -> Document)> {
    vec![
        ("wpt/css_display/display-contents-block-002-ref", css_display_display_contents_block_002_ref as fn() -> Document),
        ("wpt/css_display/display-contents-dynamic-pseudo-insertion-001-ref", css_display_display_contents_dynamic_pseudo_insertion_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-flex-001-ref", css_display_display_contents_flex_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-flex-002-ref", css_display_display_contents_flex_002_ref as fn() -> Document),
        ("wpt/css_display/display-contents-flex-002", css_display_display_contents_flex_002 as fn() -> Document),
        ("wpt/css_display/display-contents-flex-003", css_display_display_contents_flex_003 as fn() -> Document),
        ("wpt/css_display/display-contents-inline-flex-001-ref", css_display_display_contents_inline_flex_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-inline-flex-001", css_display_display_contents_inline_flex_001 as fn() -> Document),
        ("wpt/css_display/display-contents-list-001-ref", css_display_display_contents_list_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-list-001", css_display_display_contents_list_001 as fn() -> Document),
        ("wpt/css_display/display-contents-multicol-001-ref", css_display_display_contents_multicol_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-multicol-001", css_display_display_contents_multicol_001 as fn() -> Document),
        ("wpt/css_display/display-contents-pass-green-no-red-ref", css_display_display_contents_pass_green_no_red_ref as fn() -> Document),
        ("wpt/css_display/display-contents-pass-no-red-ref", css_display_display_contents_pass_no_red_ref as fn() -> Document),
        ("wpt/css_display/display-contents-pass-ref", css_display_display_contents_pass_ref as fn() -> Document),
        ("wpt/css_display/display-contents-root-background-ref", css_display_display_contents_root_background_ref as fn() -> Document),
        ("wpt/css_display/display-contents-state-change-001-ref", css_display_display_contents_state_change_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-table-001-ref", css_display_display_contents_table_001_ref as fn() -> Document),
        ("wpt/css_display/display-contents-table-001", css_display_display_contents_table_001 as fn() -> Document),
        ("wpt/css_display/display-contents-table-002-ref", css_display_display_contents_table_002_ref as fn() -> Document),
        ("wpt/css_display/display-contents-table-002", css_display_display_contents_table_002 as fn() -> Document),
        ("wpt/css_display/display-contents-text-inherit-ref", css_display_display_contents_text_inherit_ref as fn() -> Document),
        ("wpt/css_display/display-contents-whitespace-inside-inline-ref", css_display_display_contents_whitespace_inside_inline_ref as fn() -> Document),
        ("wpt/css_display/display-first-line-002-ref", css_display_display_first_line_002_ref as fn() -> Document),
        ("wpt/css_display/display-flow-root-dynamic-ref", css_display_display_flow_root_dynamic_ref as fn() -> Document),
    ]
}
