//! WPT tests: css_box
//! Auto-generated by tools/wpt/port_wpt.py
//! DO NOT EDIT MANUALLY

use openui_dom::{Document, ElementTag, NodeId};
use openui_geometry::Length;
use openui_style::*;

use crate::base_doc;

// Source: margin-trim_block-container-non-adjoining-item-ref.html
fn css_box_margin_trim_block_container_non_adjoining_item_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.margin_bottom = Length::px(100.0);
    doc.node_mut(n1).style.padding_bottom = Length::px(50.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Block;
    doc.append_child(vp, n3);
    doc
}

// Source: margin-trim_flex-block-end-trimmed-only-ref.html
fn css_box_margin_trim_flex_block_end_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_left = Length::px(10.0);
        doc.node_mut(n3).style.margin_right = Length::px(10.0);
        doc.node_mut(n3).style.margin_top = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_left = Length::px(10.0);
        doc.node_mut(n4).style.margin_right = Length::px(10.0);
        doc.node_mut(n4).style.margin_top = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-block-start-trimmed-only-ref.html
fn css_box_margin_trim_flex_block_start_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_left = Length::px(10.0);
        doc.node_mut(n3).style.margin_right = Length::px(10.0);
        doc.node_mut(n3).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_left = Length::px(10.0);
        doc.node_mut(n4).style.margin_right = Length::px(10.0);
        doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-block-trimmed-only-ref.html
fn css_box_margin_trim_flex_block_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_left = Length::px(10.0);
        doc.node_mut(n3).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_left = Length::px(10.0);
        doc.node_mut(n4).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-column-inline-multiline-ref.html
fn css_box_margin_trim_flex_column_inline_multiline_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.flex_direction = FlexDirection::Column;
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n1, n4);
        let n5 = doc.create_node(ElementTag::Div);
        doc.node_mut(n5).style.display = Display::Block;
        doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n5).style.width = Length::px(50.0);
        doc.node_mut(n5).style.height = Length::px(50.0);
        doc.append_child(n1, n5);
    doc
}

// Source: margin-trim_flex-column-style-change-triggers-layout-block-end-ref.html
fn css_box_margin_trim_flex_column_style_change_triggers_layout_block_end_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-column-style-change-triggers-layout-block-ref.html
fn css_box_margin_trim_flex_column_style_change_triggers_layout_block_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-column-style-change-triggers-layout-block-start-ref.html
fn css_box_margin_trim_flex_column_style_change_triggers_layout_block_start_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-inline-end-trimmed-only-ref.html
fn css_box_margin_trim_flex_inline_end_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.row_gap = Some(Length::px(20.0));
    doc.node_mut(n1).style.column_gap = Some(Length::px(20.0));
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_top = Length::px(10.0);
        doc.node_mut(n3).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_top = Length::px(10.0);
        doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-inline-start-trimmed-only-ref.html
fn css_box_margin_trim_flex_inline_start_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.row_gap = Some(Length::px(20.0));
    doc.node_mut(n1).style.column_gap = Some(Length::px(20.0));
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_top = Length::px(10.0);
        doc.node_mut(n3).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_top = Length::px(10.0);
        doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
        doc.node_mut(n4).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-inline-trimmed-only-ref.html
fn css_box_margin_trim_flex_inline_trimmed_only_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.row_gap = Some(Length::px(20.0));
    doc.node_mut(n1).style.column_gap = Some(Length::px(20.0));
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.margin_top = Length::px(10.0);
        doc.node_mut(n3).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.node_mut(n4).style.margin_top = Length::px(10.0);
        doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
        doc.append_child(n1, n4);
    doc
}

// Source: margin-trim_flex-row-block-multiline-ref.html
fn css_box_margin_trim_flex_row_block_multiline_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n1, n4);
        let n5 = doc.create_node(ElementTag::Div);
        doc.node_mut(n5).style.display = Display::Block;
        doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n5).style.width = Length::px(50.0);
        doc.node_mut(n5).style.height = Length::px(50.0);
        doc.append_child(n1, n5);
    doc
}

// Source: margin-trim_flex-row-style-change-triggers-layout-inline-end-ref.html
fn css_box_margin_trim_flex_row_style_change_triggers_layout_inline_end_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-row-style-change-triggers-layout-inline-ref.html
fn css_box_margin_trim_flex_row_style_change_triggers_layout_inline_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-row-style-change-triggers-layout-inline-start-ref.html
fn css_box_margin_trim_flex_row_style_change_triggers_layout_inline_start_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n1).style.border_top_width = 1;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 1;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 1;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 1;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.append_child(n1, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Flex;
    doc.node_mut(n3).style.width = Length::min_content();
    doc.node_mut(n3).style.flex_wrap = FlexWrap::Wrap;
    doc.node_mut(n3).style.border_top_width = 1;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 1;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 1;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 1;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.append_child(vp, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n3, n4);
    doc
}

// Source: margin-trim_flex-trim-all-margins-ref.html
fn css_box_margin_trim_flex_trim_all_margins_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.width = Length::min_content();
    doc.node_mut(n1).style.row_gap = Some(Length::px(20.0));
    doc.node_mut(n1).style.column_gap = Some(Length::px(20.0));
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.width = Length::px(50.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.width = Length::px(50.0);
        doc.node_mut(n4).style.height = Length::px(50.0);
        doc.append_child(n1, n4);
    doc
}

pub fn css_box_registry() -> Vec<(&'static str, fn() -> Document)> {
    vec![
        ("wpt/css_box/margin-trim_block-container-non-adjoining-item-ref", css_box_margin_trim_block_container_non_adjoining_item_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-block-end-trimmed-only-ref", css_box_margin_trim_flex_block_end_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-block-start-trimmed-only-ref", css_box_margin_trim_flex_block_start_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-block-trimmed-only-ref", css_box_margin_trim_flex_block_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-column-inline-multiline-ref", css_box_margin_trim_flex_column_inline_multiline_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-column-style-change-triggers-layout-block-end-ref", css_box_margin_trim_flex_column_style_change_triggers_layout_block_end_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-column-style-change-triggers-layout-block-ref", css_box_margin_trim_flex_column_style_change_triggers_layout_block_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-column-style-change-triggers-layout-block-start-ref", css_box_margin_trim_flex_column_style_change_triggers_layout_block_start_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-inline-end-trimmed-only-ref", css_box_margin_trim_flex_inline_end_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-inline-start-trimmed-only-ref", css_box_margin_trim_flex_inline_start_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-inline-trimmed-only-ref", css_box_margin_trim_flex_inline_trimmed_only_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-row-block-multiline-ref", css_box_margin_trim_flex_row_block_multiline_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-row-style-change-triggers-layout-inline-end-ref", css_box_margin_trim_flex_row_style_change_triggers_layout_inline_end_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-row-style-change-triggers-layout-inline-ref", css_box_margin_trim_flex_row_style_change_triggers_layout_inline_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-row-style-change-triggers-layout-inline-start-ref", css_box_margin_trim_flex_row_style_change_triggers_layout_inline_start_ref as fn() -> Document),
        ("wpt/css_box/margin-trim_flex-trim-all-margins-ref", css_box_margin_trim_flex_trim_all_margins_ref as fn() -> Document),
    ]
}
