//! WPT tests: css_position
//! Auto-generated by tools/wpt/port_wpt.py
//! DO NOT EDIT MANUALLY

use openui_dom::{Document, ElementTag, NodeId};
use openui_geometry::Length;
use openui_style::*;

use crate::base_doc;

// Source: absolute-pos-box-inside-fixed-pos-box-with-changing-height-ref.html
fn css_position_absolute_pos_box_inside_fixed_pos_box_with_changing_height_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Absolute;
    doc.node_mut(n1).style.top = Length::px(250.0);
    doc.node_mut(n1).style.left = Length::px(0.0);
    doc.node_mut(n1).style.width = Length::px(50.0);
    doc.node_mut(n1).style.height = Length::px(50.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    doc
}

// Source: block-axis-constraint-changes-for-out-of-flow-box-ref.html
fn css_position_block_axis_constraint_changes_for_out_of_flow_box_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(200.0);
    doc.node_mut(n1).style.height = Length::px(50.0);
    doc.node_mut(n1).style.background_color = Color::BLUE;
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.width = Length::px(50.0);
    doc.node_mut(n2).style.height = Length::px(50.0);
    doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Block;
    doc.node_mut(n3).style.width = Length::px(50.0);
    doc.node_mut(n3).style.height = Length::px(50.0);
    doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n3);
    let n4 = doc.create_node(ElementTag::Div);
    doc.node_mut(n4).style.display = Display::Block;
    doc.node_mut(n4).style.width = Length::px(200.0);
    doc.node_mut(n4).style.height = Length::px(50.0);
    doc.node_mut(n4).style.background_color = Color::BLUE;
    doc.append_child(vp, n4);
    doc
}

// Source: containing-block-change-scrollframe-ref.html
fn css_position_containing_block_change_scrollframe_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(400.0);
    doc.node_mut(n1).style.height = Length::px(400.0);
    doc.node_mut(n1).style.margin_top = Length::px(100.0);
    doc.node_mut(n1).style.margin_right = Length::px(100.0);
    doc.node_mut(n1).style.margin_bottom = Length::px(100.0);
    doc.node_mut(n1).style.margin_left = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(128, 0, 128, 255);
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::px(300.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n3);
        let n4 = doc.create_node(ElementTag::Div);
        doc.node_mut(n4).style.display = Display::Block;
        doc.node_mut(n4).style.position = Position::Absolute;
        doc.node_mut(n4).style.width = Length::px(100.0);
        doc.node_mut(n4).style.height = Length::px(100.0);
        doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n4).style.top = Length::px(0.0);
        doc.node_mut(n4).style.left = Length::px(0.0);
        doc.append_child(n1, n4);
    doc
}

// Source: hypothetical-dynamic-change-001-ref.html
fn css_position_hypothetical_dynamic_change_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.position = Position::Fixed;
    doc.node_mut(n1).style.left = Length::px(100.0);
    doc.node_mut(n1).style.top = Length::px(0.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    doc
}

// Source: position-absolute-center-001.html
fn css_position_position_absolute_center_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.flex_direction = FlexDirection::Row;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Flex;
        doc.node_mut(n2).style.justify_content = ContentAlignment::new(ContentPosition::Center);
        doc.node_mut(n2).style.flex_grow = 1.0;
        doc.node_mut(n2).style.margin_top = Length::px(10.0);
        doc.node_mut(n2).style.margin_right = Length::px(10.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(10.0);
        doc.node_mut(n2).style.margin_left = Length::px(10.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.position = Position::Absolute;
            doc.node_mut(n3).style.top = Length::px(0.0);
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Span);
                doc.node_mut(n4).style.display = Display::InlineBlock;
                doc.node_mut(n4).style.width = Length::px(50.0);
                doc.node_mut(n4).style.height = Length::px(10.0);
                doc.append_child(n3, n4);
                let n5 = doc.create_node(ElementTag::Span);
                doc.node_mut(n5).style.display = Display::InlineBlock;
                doc.node_mut(n5).style.width = Length::px(50.0);
                doc.node_mut(n5).style.height = Length::px(10.0);
                doc.append_child(n3, n5);
        let n6 = doc.create_node(ElementTag::Div);
        doc.node_mut(n6).style.display = Display::Block;
        doc.node_mut(n6).style.flex_grow = 1.0;
        doc.node_mut(n6).style.height = Length::px(100.0);
        doc.node_mut(n6).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n6);
    doc
}

// Source: position-absolute-center-003.html
fn css_position_position_absolute_center_003() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.box_sizing = BoxSizing::BorderBox;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.box_sizing = BoxSizing::BorderBox;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.node_mut(n2).style.background_color = Color::RED;
        doc.node_mut(n2).style.border_top_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_top_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_right_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_right_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_bottom_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_bottom_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_left_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_left_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_top_width = 30;
        doc.node_mut(n2).style.border_right_width = 20;
        doc.node_mut(n2).style.border_bottom_width = 20;
        doc.node_mut(n2).style.border_left_width = 30;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.box_sizing = BoxSizing::BorderBox;
        doc.node_mut(n3).style.display = Display::Flex;
        doc.node_mut(n3).style.align_items = ItemAlignment::new(ItemPosition::Center);
        doc.node_mut(n3).style.justify_content = ContentAlignment::new(ContentPosition::Center);
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Absolute;
            doc.node_mut(n4).style.width = Length::px(50.0);
            doc.node_mut(n4).style.height = Length::px(50.0);
            doc.node_mut(n4).style.margin_left = Length::px(10.0);
            doc.node_mut(n4).style.margin_top = Length::px(10.0);
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n3, n4);
    doc
}

// Source: position-absolute-center-004.html
fn css_position_position_absolute_center_004() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.box_sizing = BoxSizing::BorderBox;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.box_sizing = BoxSizing::BorderBox;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.node_mut(n2).style.background_color = Color::RED;
        doc.node_mut(n2).style.border_top_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_top_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_right_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_right_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_bottom_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_bottom_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_left_style = BorderStyle::Solid;
        doc.node_mut(n2).style.border_left_color = StyleColor::Resolved(Color::from_rgba8(0, 128, 0, 255));
        doc.node_mut(n2).style.border_top_width = 20;
        doc.node_mut(n2).style.border_right_width = 30;
        doc.node_mut(n2).style.border_bottom_width = 30;
        doc.node_mut(n2).style.border_left_width = 20;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.box_sizing = BoxSizing::BorderBox;
        doc.node_mut(n3).style.display = Display::Flex;
        doc.node_mut(n3).style.align_items = ItemAlignment::new(ItemPosition::Center);
        doc.node_mut(n3).style.justify_content = ContentAlignment::new(ContentPosition::Center);
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Absolute;
            doc.node_mut(n4).style.width = Length::px(50.0);
            doc.node_mut(n4).style.height = Length::px(50.0);
            doc.node_mut(n4).style.margin_right = Length::px(10.0);
            doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n3, n4);
    doc
}

// Source: position-absolute-fit-content.html
fn css_position_position_absolute_fit_content() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(200.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.node_mut(n2).style.top = Length::px(0.0);
        doc.node_mut(n2).style.bottom = Length::px(0.0);
        doc.node_mut(n2).style.left = Length::px(0.0);
        doc.node_mut(n2).style.right = Length::px(0.0);
        doc.node_mut(n2).style.max_height = Length::fit_content();
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.append_child(n2, n3);
    doc
}

// Source: position-absolute-iframe-print-ref.html
fn css_position_position_absolute_iframe_print_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Absolute;
    doc.node_mut(n1).style.top = Length::px(0.0);
    doc.node_mut(n1).style.left = Length::px(0.0);
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.height = Length::px(1200.0);
    doc.append_child(vp, n2);
    doc
}

// Source: position-absolute-in-inline-003.html
fn css_position_position_absolute_in_inline_003() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.color = Color::WHITE;
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::px(60.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Span);
        doc.node_mut(n3).style.position = Position::Relative;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n3, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.node_mut(n5).style.position = Position::Absolute;
            doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n5).style.height = Length::px(100.0);
            doc.node_mut(n5).style.width = Length::px(100.0);
            doc.node_mut(n5).style.top = Length::px(-60.0);
            doc.append_child(n3, n5);
    doc
}

// Source: position-absolute-in-inline-004.html
fn css_position_position_absolute_in_inline_004() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.color = Color::WHITE;
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Span);
        doc.node_mut(n3).style.position = Position::Relative;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Absolute;
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n4).style.height = Length::px(100.0);
            doc.node_mut(n4).style.width = Length::px(50.0);
            doc.node_mut(n4).style.top = Length::px(-50.0);
            doc.node_mut(n4).style.left = Length::px(-30.0);
            doc.append_child(n3, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.display = Display::Block;
            doc.node_mut(n5).style.position = Position::Absolute;
            doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n5).style.height = Length::px(100.0);
            doc.node_mut(n5).style.width = Length::px(50.0);
            doc.node_mut(n5).style.top = Length::px(-50.0);
            doc.node_mut(n5).style.left = Length::px(-80.0);
            doc.append_child(n3, n5);
    doc
}

// Source: position-absolute-large-negative-inset-ref.html
fn css_position_position_absolute_large_negative_inset_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n1).style.width = Length::px(50.0);
    doc.node_mut(n1).style.height = Length::px(50.0);
    doc.append_child(vp, n1);
    doc
}

// Source: position-absolute-multicol-001.html
fn css_position_position_absolute_multicol_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.column_count = Some(2);
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Absolute;
            doc.append_child(n3, n4);
    doc
}

// Source: position-change-ref.html
fn css_position_position_change_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.overflow_y = Overflow::Scroll;
        doc.node_mut(n2).style.width = Length::px(400.0);
        doc.node_mut(n2).style.height = Length::px(400.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.width = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n2, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.height = Length::px(700.0);
            doc.append_child(n2, n4);
    doc
}

// Source: position-fixed-dynamic-transformed-sibling-ref.html
fn css_position_position_fixed_dynamic_transformed_sibling_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Fixed;
    doc.node_mut(n1).style.top = Length::px(0.0);
    doc.node_mut(n1).style.left = Length::px(0.0);
    doc.node_mut(n1).style.width = Length::percent(100.0);
    doc.node_mut(n1).style.height = Length::px(50.0);
    doc.node_mut(n1).style.background_color = Color::BLUE;
    doc.append_child(vp, n1);
    doc
}

// Source: position-fixed-overflow-print-ref.html
fn css_position_position_fixed_overflow_print_ref() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(128, 0, 128, 255);
    doc.node_mut(n1).style.width = Length::percent(50.0);
    doc.node_mut(n1).style.height = Length::px(600.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(128, 0, 128, 255);
        doc.node_mut(n2).style.top = Length::px(0.0);
        doc.node_mut(n2).style.left = Length::percent(50.0);
        doc.node_mut(n2).style.width = Length::percent(50.0);
        doc.node_mut(n2).style.height = Length::px(600.0);
        doc.append_child(n1, n2);
    doc
}

// Source: position-fixed-overflow-print.html
fn css_position_position_fixed_overflow_print() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(128, 0, 128, 255);
    doc.node_mut(n1).style.width = Length::px(800.0);
    doc.node_mut(n1).style.height = Length::px(600.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.position = Position::Fixed;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(128, 0, 128, 255);
        doc.node_mut(n2).style.top = Length::px(0.0);
        doc.node_mut(n2).style.left = Length::percent(50.0);
        doc.node_mut(n2).style.width = Length::px(800.0);
        doc.node_mut(n2).style.height = Length::px(600.0);
        doc.append_child(n1, n2);
    doc
}

// Source: position-fixed-scroll-nested-fixed-ref.html
fn css_position_position_fixed_scroll_nested_fixed_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(200.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.height = Length::px(4900.0);
    doc.append_child(vp, n2);
    doc
}

// Source: position-fixed-scroll-overlap-ref.html
fn css_position_position_fixed_scroll_overlap_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(8000.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    doc
}

// Source: position-relative-001.html
fn css_position_position_relative_001() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Span);
        doc.node_mut(n2).style.position = Position::Relative;
        doc.node_mut(n2).style.top = Length::percent(100.0);
        doc.node_mut(n2).style.left = Length::percent(100.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.width = Length::px(100.0);
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n3).style.position = Position::Relative;
            doc.node_mut(n3).style.top = Length::px(-100.0);
            doc.node_mut(n3).style.left = Length::px(-100.0);
            doc.append_child(n2, n3);
    doc
}

// Source: position-relative-002.html
fn css_position_position_relative_002() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Span);
        doc.node_mut(n2).style.position = Position::Relative;
        doc.node_mut(n2).style.top = Length::px(100.0);
        doc.node_mut(n2).style.left = Length::px(100.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.width = Length::px(100.0);
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n3).style.position = Position::Relative;
            doc.node_mut(n3).style.top = Length::percent(-100.0);
            doc.node_mut(n3).style.left = Length::percent(-100.0);
            doc.append_child(n2, n3);
    doc
}

// Source: position-relative-003.html
fn css_position_position_relative_003() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Span);
        doc.node_mut(n2).style.position = Position::Relative;
        doc.node_mut(n2).style.top = Length::percent(100.0);
        doc.node_mut(n2).style.left = Length::percent(100.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Span);
            doc.node_mut(n3).style.position = Position::Relative;
            doc.node_mut(n3).style.top = Length::px(-100.0);
            doc.node_mut(n3).style.left = Length::px(-100.0);
            doc.append_child(n2, n3);
                let n4 = doc.create_node(ElementTag::Div);
                doc.node_mut(n4).style.display = Display::Block;
                doc.node_mut(n4).style.width = Length::px(100.0);
                doc.node_mut(n4).style.height = Length::px(100.0);
                doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
                doc.node_mut(n4).style.position = Position::Fixed;
                doc.append_child(n3, n4);
    doc
}

// Source: position-relative-006.html
fn css_position_position_relative_006() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.min_height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.top = Length::percent(-10000.0);
        doc.node_mut(n2).style.position = Position::Relative;
        doc.append_child(n1, n2);
    doc
}

// Source: position-relative-007.html
fn css_position_position_relative_007() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.min_height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n2).style.position = Position::Relative;
        doc.append_child(n1, n2);
    doc
}

// Source: static-position_htb-ref.html
fn css_position_static_position_htb_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n1).style.height = Length::px(16.0);
    doc.node_mut(n1).style.border_top_width = 3;
    doc.node_mut(n1).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_right_width = 3;
    doc.node_mut(n1).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_bottom_width = 3;
    doc.node_mut(n1).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.border_left_width = 3;
    doc.node_mut(n1).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n1).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n1).style.width = Length::px(400.0);
    doc.node_mut(n1).style.margin_top = Length::px(16.0);
    doc.node_mut(n1).style.margin_right = Length::px(0.0);
    doc.node_mut(n1).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n1).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n2).style.height = Length::px(16.0);
    doc.node_mut(n2).style.border_top_width = 3;
    doc.node_mut(n2).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n2).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n2).style.border_right_width = 3;
    doc.node_mut(n2).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n2).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n2).style.border_bottom_width = 3;
    doc.node_mut(n2).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n2).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n2).style.border_left_width = 3;
    doc.node_mut(n2).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n2).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n2).style.width = Length::px(400.0);
    doc.node_mut(n2).style.margin_top = Length::px(16.0);
    doc.node_mut(n2).style.margin_right = Length::px(0.0);
    doc.node_mut(n2).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n2).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n2);
    let n3 = doc.create_node(ElementTag::Div);
    doc.node_mut(n3).style.display = Display::Block;
    doc.node_mut(n3).style.height = Length::px(16.0);
    doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n3).style.border_top_width = 3;
    doc.node_mut(n3).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_right_width = 3;
    doc.node_mut(n3).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_bottom_width = 3;
    doc.node_mut(n3).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.border_left_width = 3;
    doc.node_mut(n3).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n3).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n3).style.width = Length::px(400.0);
    doc.node_mut(n3).style.margin_top = Length::px(16.0);
    doc.node_mut(n3).style.margin_right = Length::px(0.0);
    doc.node_mut(n3).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n3).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n3);
    let n4 = doc.create_node(ElementTag::Div);
    doc.node_mut(n4).style.display = Display::Block;
    doc.node_mut(n4).style.height = Length::px(16.0);
    doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n4).style.border_top_width = 3;
    doc.node_mut(n4).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n4).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n4).style.border_right_width = 3;
    doc.node_mut(n4).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n4).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n4).style.border_bottom_width = 3;
    doc.node_mut(n4).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n4).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n4).style.border_left_width = 3;
    doc.node_mut(n4).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n4).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n4).style.width = Length::px(400.0);
    doc.node_mut(n4).style.margin_top = Length::px(16.0);
    doc.node_mut(n4).style.margin_right = Length::px(0.0);
    doc.node_mut(n4).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n4).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n4);
    let n5 = doc.create_node(ElementTag::Div);
    doc.node_mut(n5).style.display = Display::Block;
    doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n5).style.height = Length::px(16.0);
    doc.node_mut(n5).style.border_top_width = 3;
    doc.node_mut(n5).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n5).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n5).style.border_right_width = 3;
    doc.node_mut(n5).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n5).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n5).style.border_bottom_width = 3;
    doc.node_mut(n5).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n5).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n5).style.border_left_width = 3;
    doc.node_mut(n5).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n5).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n5).style.width = Length::px(400.0);
    doc.node_mut(n5).style.margin_top = Length::px(16.0);
    doc.node_mut(n5).style.margin_right = Length::px(0.0);
    doc.node_mut(n5).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n5).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n5);
    let n6 = doc.create_node(ElementTag::Div);
    doc.node_mut(n6).style.display = Display::Block;
    doc.node_mut(n6).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n6).style.height = Length::px(16.0);
    doc.node_mut(n6).style.border_top_width = 3;
    doc.node_mut(n6).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n6).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n6).style.border_right_width = 3;
    doc.node_mut(n6).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n6).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n6).style.border_bottom_width = 3;
    doc.node_mut(n6).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n6).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n6).style.border_left_width = 3;
    doc.node_mut(n6).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n6).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n6).style.width = Length::px(400.0);
    doc.node_mut(n6).style.margin_top = Length::px(16.0);
    doc.node_mut(n6).style.margin_right = Length::px(0.0);
    doc.node_mut(n6).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n6).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n6);
    let n7 = doc.create_node(ElementTag::Div);
    doc.node_mut(n7).style.display = Display::Block;
    doc.node_mut(n7).style.height = Length::px(16.0);
    doc.node_mut(n7).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n7).style.border_top_width = 3;
    doc.node_mut(n7).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n7).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n7).style.border_right_width = 3;
    doc.node_mut(n7).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n7).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n7).style.border_bottom_width = 3;
    doc.node_mut(n7).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n7).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n7).style.border_left_width = 3;
    doc.node_mut(n7).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n7).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n7).style.width = Length::px(400.0);
    doc.node_mut(n7).style.margin_top = Length::px(16.0);
    doc.node_mut(n7).style.margin_right = Length::px(0.0);
    doc.node_mut(n7).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n7).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n7);
    let n8 = doc.create_node(ElementTag::Div);
    doc.node_mut(n8).style.display = Display::Block;
    doc.node_mut(n8).style.height = Length::px(16.0);
    doc.node_mut(n8).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n8).style.border_top_width = 3;
    doc.node_mut(n8).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n8).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n8).style.border_right_width = 3;
    doc.node_mut(n8).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n8).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n8).style.border_bottom_width = 3;
    doc.node_mut(n8).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n8).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n8).style.border_left_width = 3;
    doc.node_mut(n8).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n8).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n8).style.width = Length::px(400.0);
    doc.node_mut(n8).style.margin_top = Length::px(16.0);
    doc.node_mut(n8).style.margin_right = Length::px(0.0);
    doc.node_mut(n8).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n8).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n8);
    let n9 = doc.create_node(ElementTag::Div);
    doc.node_mut(n9).style.display = Display::Block;
    doc.node_mut(n9).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n9).style.height = Length::px(16.0);
    doc.node_mut(n9).style.border_top_width = 3;
    doc.node_mut(n9).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n9).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n9).style.border_right_width = 3;
    doc.node_mut(n9).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n9).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n9).style.border_bottom_width = 3;
    doc.node_mut(n9).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n9).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n9).style.border_left_width = 3;
    doc.node_mut(n9).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n9).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n9).style.width = Length::px(400.0);
    doc.node_mut(n9).style.margin_top = Length::px(16.0);
    doc.node_mut(n9).style.margin_right = Length::px(0.0);
    doc.node_mut(n9).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n9).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n9);
    let n10 = doc.create_node(ElementTag::Div);
    doc.node_mut(n10).style.display = Display::Block;
    doc.node_mut(n10).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n10).style.height = Length::px(16.0);
    doc.node_mut(n10).style.border_top_width = 3;
    doc.node_mut(n10).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n10).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n10).style.border_right_width = 3;
    doc.node_mut(n10).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n10).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n10).style.border_bottom_width = 3;
    doc.node_mut(n10).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n10).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n10).style.border_left_width = 3;
    doc.node_mut(n10).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n10).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n10).style.width = Length::px(400.0);
    doc.node_mut(n10).style.margin_top = Length::px(16.0);
    doc.node_mut(n10).style.margin_right = Length::px(0.0);
    doc.node_mut(n10).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n10).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n10);
    let n11 = doc.create_node(ElementTag::Div);
    doc.node_mut(n11).style.display = Display::Block;
    doc.node_mut(n11).style.height = Length::px(16.0);
    doc.node_mut(n11).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n11).style.border_top_width = 3;
    doc.node_mut(n11).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n11).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n11).style.border_right_width = 3;
    doc.node_mut(n11).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n11).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n11).style.border_bottom_width = 3;
    doc.node_mut(n11).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n11).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n11).style.border_left_width = 3;
    doc.node_mut(n11).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n11).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n11).style.width = Length::px(400.0);
    doc.node_mut(n11).style.margin_top = Length::px(16.0);
    doc.node_mut(n11).style.margin_right = Length::px(0.0);
    doc.node_mut(n11).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n11).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n11);
    let n12 = doc.create_node(ElementTag::Div);
    doc.node_mut(n12).style.display = Display::Block;
    doc.node_mut(n12).style.height = Length::px(16.0);
    doc.node_mut(n12).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n12).style.border_top_width = 3;
    doc.node_mut(n12).style.border_top_style = BorderStyle::Solid;
    doc.node_mut(n12).style.border_top_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n12).style.border_right_width = 3;
    doc.node_mut(n12).style.border_right_style = BorderStyle::Solid;
    doc.node_mut(n12).style.border_right_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n12).style.border_bottom_width = 3;
    doc.node_mut(n12).style.border_bottom_style = BorderStyle::Solid;
    doc.node_mut(n12).style.border_bottom_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n12).style.border_left_width = 3;
    doc.node_mut(n12).style.border_left_style = BorderStyle::Solid;
    doc.node_mut(n12).style.border_left_color = StyleColor::Resolved(Color::BLACK);
    doc.node_mut(n12).style.width = Length::px(400.0);
    doc.node_mut(n12).style.margin_top = Length::px(16.0);
    doc.node_mut(n12).style.margin_right = Length::px(0.0);
    doc.node_mut(n12).style.margin_bottom = Length::px(16.0);
    doc.node_mut(n12).style.margin_left = Length::px(0.0);
    doc.append_child(vp, n12);
    doc
}

// Source: static-position_inline-level-absolute-in-block-level-context-013.html
fn css_position_static_position_inline_level_absolute_in_block_level_context_013() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.float = Float::Left;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.clear = Clear::Both;
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.background_color = Color::RED;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.position = Position::Absolute;
            doc.node_mut(n4).style.display = Display::Inline;
            doc.node_mut(n4).style.width = Length::px(100.0);
            doc.node_mut(n4).style.height = Length::px(50.0);
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n3, n4);
    doc
}

// Source: static-position_inline-level-absolute-in-block-level-context-014.html
fn css_position_static_position_inline_level_absolute_in_block_level_context_014() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.float = Float::Left;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.clear = Clear::Both;
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(50.0);
        doc.node_mut(n3).style.background_color = Color::RED;
        doc.append_child(n1, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.append_child(n3, n4);
            let n5 = doc.create_node(ElementTag::Div);
            doc.node_mut(n5).style.position = Position::Absolute;
            doc.node_mut(n5).style.display = Display::Inline;
            doc.node_mut(n5).style.width = Length::px(100.0);
            doc.node_mut(n5).style.height = Length::px(50.0);
            doc.node_mut(n5).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n3, n5);
    doc
}

// Source: sticky_position-sticky-bottom-004.html
fn css_position_sticky_position_sticky_bottom_004() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.margin_top = Length::px(-100.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.append_child(n2, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Sticky;
            doc.node_mut(n4).style.bottom = Length::px(0.0);
            doc.node_mut(n4).style.height = Length::px(100.0);
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n2, n4);
    doc
}

// Source: sticky_position-sticky-bottom-005.html
fn css_position_sticky_position_sticky_bottom_005() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.padding_top = Length::px(200.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.margin_top = Length::px(-200.0);
            doc.append_child(n2, n3);
            let n4 = doc.create_node(ElementTag::Div);
            doc.node_mut(n4).style.display = Display::Block;
            doc.node_mut(n4).style.position = Position::Sticky;
            doc.node_mut(n4).style.bottom = Length::px(0.0);
            doc.node_mut(n4).style.height = Length::px(100.0);
            doc.node_mut(n4).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.append_child(n2, n4);
    doc
}

// Source: sticky_position-sticky-bottom-006.html
fn css_position_sticky_position_sticky_bottom_006() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.margin_top = Length::px(-100.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.position = Position::Sticky;
        doc.node_mut(n3).style.bottom = Length::px(0.0);
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.background_color = Color::RED;
        doc.append_child(n1, n3);
    doc
}

// Source: sticky_position-sticky-change-top-ref.html
fn css_position_sticky_position_sticky_change_top_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.node_mut(n1).style.position = Position::Sticky;
    doc.node_mut(n1).style.top = Length::px(200.0);
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.height = Length::px(1200.0);
    doc.append_child(vp, n2);
    doc
}

// Source: sticky_position-sticky-column-reverse-flex-ref.html
fn css_position_sticky_position_sticky_column_reverse_flex_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.flex_direction = FlexDirection::ColumnReverse;
    doc.node_mut(n1).style.overflow_y = Overflow::Scroll;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.position = Position::Absolute;
        doc.node_mut(n2).style.bottom = Length::px(0.0);
        doc.node_mut(n2).style.height = Length::px(50.0);
        doc.node_mut(n2).style.width = Length::px(50.0);
        doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.min_height = Length::px(400.0);
        doc.append_child(n1, n3);
    doc
}

// Source: sticky_position-sticky-escape-scroller-001-ref.html
fn css_position_sticky_position_sticky_escape_scroller_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(200.0);
    doc.node_mut(n1).style.height = Length::px(200.0);
    doc.node_mut(n1).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n1);
    doc
}

// Source: sticky_position-sticky-fixed-ancestor-003.html
fn css_position_sticky_position_sticky_fixed_ancestor_003() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.height = Length::percent(100.0);
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    doc.node_mut(vp).style.width = Length::percent(100.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.node_mut(n1).style.color = Color::from_rgba8(255, 255, 0, 255);
    doc.node_mut(n1).style.position = Position::Fixed;
    doc.node_mut(n1).style.height = Length::percent(100.0);
    doc.node_mut(n1).style.margin_top = Length::px(0.0);
    doc.node_mut(n1).style.margin_right = Length::px(0.0);
    doc.node_mut(n1).style.margin_bottom = Length::px(0.0);
    doc.node_mut(n1).style.margin_left = Length::px(0.0);
    doc.node_mut(n1).style.width = Length::percent(100.0);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::percent(100.0);
        doc.node_mut(n2).style.margin_top = Length::px(0.0);
        doc.node_mut(n2).style.margin_right = Length::px(0.0);
        doc.node_mut(n2).style.margin_bottom = Length::px(0.0);
        doc.node_mut(n2).style.margin_left = Length::px(0.0);
        doc.node_mut(n2).style.width = Length::percent(100.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
        doc.node_mut(n3).style.bottom = Length::px(0.0);
        doc.node_mut(n3).style.color = Color::WHITE;
        doc.node_mut(n3).style.position = Position::Sticky;
        doc.node_mut(n3).style.height = Length::percent(100.0);
        doc.node_mut(n3).style.margin_top = Length::px(0.0);
        doc.node_mut(n3).style.margin_right = Length::px(0.0);
        doc.node_mut(n3).style.margin_bottom = Length::px(0.0);
        doc.node_mut(n3).style.margin_left = Length::px(0.0);
        doc.node_mut(n3).style.width = Length::percent(100.0);
        doc.append_child(n1, n3);
    doc
}

// Source: sticky_position-sticky-margins-002.html
fn css_position_sticky_position_sticky_margins_002() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Flex;
        doc.node_mut(n2).style.flex_direction = FlexDirection::Column;
        doc.node_mut(n2).style.height = Length::px(500.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.width = Length::px(100.0);
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n3).style.position = Position::Sticky;
            doc.node_mut(n3).style.margin_top = Length::auto();
            doc.node_mut(n3).style.bottom = Length::px(0.0);
            doc.append_child(n2, n3);
    doc
}

// Source: sticky_position-sticky-margins-003.html
fn css_position_sticky_position_sticky_margins_003() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.width = Length::px(100.0);
    doc.node_mut(n1).style.height = Length::px(100.0);
    doc.node_mut(n1).style.overflow_x = Overflow::Hidden;
    doc.node_mut(n1).style.overflow_y = Overflow::Hidden;
    doc.node_mut(n1).style.background_color = Color::RED;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(500.0);
        doc.append_child(n1, n2);
            let n3 = doc.create_node(ElementTag::Div);
            doc.node_mut(n3).style.display = Display::Block;
            doc.node_mut(n3).style.width = Length::px(100.0);
            doc.node_mut(n3).style.height = Length::px(100.0);
            doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 128, 0, 255);
            doc.node_mut(n3).style.position = Position::Sticky;
            doc.node_mut(n3).style.margin_left = Length::auto();
            doc.node_mut(n3).style.right = Length::px(0.0);
            doc.append_child(n2, n3);
    doc
}

// Source: sticky_position-sticky-padding-001-ref.html
fn css_position_sticky_position_sticky_padding_001_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.width = Length::px(300.0);
    doc.node_mut(n1).style.height = Length::px(210.0);
    doc.node_mut(n1).style.padding_top = Length::px(10.0);
    doc.node_mut(n1).style.padding_right = Length::px(10.0);
    doc.node_mut(n1).style.padding_bottom = Length::px(10.0);
    doc.node_mut(n1).style.padding_left = Length::px(10.0);
    doc.node_mut(n1).style.padding_top = Length::px(0.0);
    doc.node_mut(n1).style.margin_top = Length::px(10.0);
    doc.node_mut(n1).style.margin_right = Length::px(10.0);
    doc.node_mut(n1).style.margin_bottom = Length::px(10.0);
    doc.node_mut(n1).style.margin_left = Length::px(10.0);
    doc.node_mut(n1).style.float = Float::Left;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(221, 221, 221, 255);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(100.0);
        doc.node_mut(n2).style.background_color = Color::BLUE;
        doc.node_mut(n2).style.height = Length::px(210.0);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.position = Position::Absolute;
        doc.node_mut(n3).style.width = Length::px(10.0);
        doc.node_mut(n3).style.height = Length::px(10.0);
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 255, 255, 255);
        doc.node_mut(n3).style.top = Length::px(210.0);
        doc.append_child(n1, n3);
    let n4 = doc.create_node(ElementTag::Div);
    doc.node_mut(n4).style.display = Display::Block;
    doc.node_mut(n4).style.position = Position::Relative;
    doc.node_mut(n4).style.width = Length::px(300.0);
    doc.node_mut(n4).style.height = Length::px(210.0);
    doc.node_mut(n4).style.padding_top = Length::px(10.0);
    doc.node_mut(n4).style.padding_right = Length::px(10.0);
    doc.node_mut(n4).style.padding_bottom = Length::px(10.0);
    doc.node_mut(n4).style.padding_left = Length::px(10.0);
    doc.node_mut(n4).style.padding_top = Length::px(0.0);
    doc.node_mut(n4).style.margin_top = Length::px(10.0);
    doc.node_mut(n4).style.margin_right = Length::px(10.0);
    doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
    doc.node_mut(n4).style.margin_left = Length::px(10.0);
    doc.node_mut(n4).style.float = Float::Left;
    doc.node_mut(n4).style.background_color = Color::from_rgba8(221, 221, 221, 255);
    doc.append_child(vp, n4);
        let n5 = doc.create_node(ElementTag::Div);
        doc.node_mut(n5).style.display = Display::Block;
        doc.node_mut(n5).style.width = Length::px(100.0);
        doc.node_mut(n5).style.background_color = Color::BLUE;
        doc.node_mut(n5).style.height = Length::px(210.0);
        doc.append_child(n4, n5);
        let n6 = doc.create_node(ElementTag::Div);
        doc.node_mut(n6).style.display = Display::Block;
        doc.node_mut(n6).style.position = Position::Absolute;
        doc.node_mut(n6).style.width = Length::px(10.0);
        doc.node_mut(n6).style.height = Length::px(10.0);
        doc.node_mut(n6).style.background_color = Color::from_rgba8(0, 255, 255, 255);
        doc.node_mut(n6).style.top = Length::px(210.0);
        doc.append_child(n4, n6);
    doc
}

// Source: sticky_position-sticky-padding-002-ref.html
fn css_position_sticky_position_sticky_padding_002_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.position = Position::Relative;
    doc.node_mut(n1).style.width = Length::px(210.0);
    doc.node_mut(n1).style.height = Length::px(300.0);
    doc.node_mut(n1).style.padding_top = Length::px(10.0);
    doc.node_mut(n1).style.padding_right = Length::px(10.0);
    doc.node_mut(n1).style.padding_bottom = Length::px(10.0);
    doc.node_mut(n1).style.padding_left = Length::px(10.0);
    doc.node_mut(n1).style.padding_left = Length::px(0.0);
    doc.node_mut(n1).style.margin_top = Length::px(10.0);
    doc.node_mut(n1).style.margin_right = Length::px(10.0);
    doc.node_mut(n1).style.margin_bottom = Length::px(10.0);
    doc.node_mut(n1).style.margin_left = Length::px(10.0);
    doc.node_mut(n1).style.float = Float::Left;
    doc.node_mut(n1).style.background_color = Color::from_rgba8(221, 221, 221, 255);
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.width = Length::px(210.0);
        doc.node_mut(n2).style.background_color = Color::BLUE;
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.position = Position::Absolute;
        doc.node_mut(n3).style.width = Length::px(10.0);
        doc.node_mut(n3).style.height = Length::px(10.0);
        doc.node_mut(n3).style.background_color = Color::from_rgba8(0, 255, 255, 255);
        doc.node_mut(n3).style.top = Length::px(0.0);
        doc.node_mut(n3).style.left = Length::px(210.0);
        doc.append_child(n1, n3);
    let n4 = doc.create_node(ElementTag::Div);
    doc.node_mut(n4).style.display = Display::Block;
    doc.node_mut(n4).style.position = Position::Relative;
    doc.node_mut(n4).style.width = Length::px(210.0);
    doc.node_mut(n4).style.height = Length::px(300.0);
    doc.node_mut(n4).style.padding_top = Length::px(10.0);
    doc.node_mut(n4).style.padding_right = Length::px(10.0);
    doc.node_mut(n4).style.padding_bottom = Length::px(10.0);
    doc.node_mut(n4).style.padding_left = Length::px(10.0);
    doc.node_mut(n4).style.padding_left = Length::px(0.0);
    doc.node_mut(n4).style.margin_top = Length::px(10.0);
    doc.node_mut(n4).style.margin_right = Length::px(10.0);
    doc.node_mut(n4).style.margin_bottom = Length::px(10.0);
    doc.node_mut(n4).style.margin_left = Length::px(10.0);
    doc.node_mut(n4).style.float = Float::Left;
    doc.node_mut(n4).style.background_color = Color::from_rgba8(221, 221, 221, 255);
    doc.append_child(vp, n4);
        let n5 = doc.create_node(ElementTag::Div);
        doc.node_mut(n5).style.display = Display::Block;
        doc.node_mut(n5).style.height = Length::px(100.0);
        doc.node_mut(n5).style.width = Length::px(210.0);
        doc.node_mut(n5).style.background_color = Color::BLUE;
        doc.append_child(n4, n5);
        let n6 = doc.create_node(ElementTag::Div);
        doc.node_mut(n6).style.display = Display::Block;
        doc.node_mut(n6).style.position = Position::Absolute;
        doc.node_mut(n6).style.width = Length::px(10.0);
        doc.node_mut(n6).style.height = Length::px(10.0);
        doc.node_mut(n6).style.background_color = Color::from_rgba8(0, 255, 255, 255);
        doc.node_mut(n6).style.top = Length::px(0.0);
        doc.node_mut(n6).style.left = Length::px(210.0);
        doc.append_child(n4, n6);
    doc
}

// Source: sticky_position-sticky-rtl-ref.html
fn css_position_sticky_position_sticky_rtl_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.overflow_x = Overflow::Auto;
    doc.node_mut(n1).style.overflow_y = Overflow::Auto;
    doc.node_mut(n1).style.width = Length::px(500.0);
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(1900.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.flex_shrink = 0.0;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(173, 216, 230, 255);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.position = Position::Absolute;
        doc.node_mut(n3).style.left = Length::px(0.0);
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.flex_shrink = 0.0;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(144, 238, 144, 255);
        doc.append_child(n1, n3);
    doc
}

// Source: sticky_position-sticky-rtl.html
fn css_position_sticky_position_sticky_rtl() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Flex;
    doc.node_mut(n1).style.overflow_x = Overflow::Auto;
    doc.node_mut(n1).style.overflow_y = Overflow::Auto;
    doc.node_mut(n1).style.width = Length::px(500.0);
    doc.node_mut(n1).style.position = Position::Relative;
    doc.append_child(vp, n1);
        let n2 = doc.create_node(ElementTag::Div);
        doc.node_mut(n2).style.display = Display::Block;
        doc.node_mut(n2).style.width = Length::px(1900.0);
        doc.node_mut(n2).style.height = Length::px(100.0);
        doc.node_mut(n2).style.flex_shrink = 0.0;
        doc.node_mut(n2).style.background_color = Color::from_rgba8(173, 216, 230, 255);
        doc.append_child(n1, n2);
        let n3 = doc.create_node(ElementTag::Div);
        doc.node_mut(n3).style.display = Display::Block;
        doc.node_mut(n3).style.position = Position::Sticky;
        doc.node_mut(n3).style.left = Length::px(0.0);
        doc.node_mut(n3).style.width = Length::px(100.0);
        doc.node_mut(n3).style.height = Length::px(100.0);
        doc.node_mut(n3).style.flex_shrink = 0.0;
        doc.node_mut(n3).style.background_color = Color::from_rgba8(144, 238, 144, 255);
        doc.append_child(n1, n3);
    doc
}

// Source: sticky_position-sticky-stacking-context-ref.html
fn css_position_sticky_position_sticky_stacking_context_ref() -> Document {
    let (mut doc, vp) = base_doc();
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.width = Length::px(200.0);
    doc.node_mut(n2).style.height = Length::px(200.0);
    doc.node_mut(n2).style.background_color = Color::from_rgba8(0, 128, 0, 255);
    doc.append_child(vp, n2);
    doc
}

// Source: resources_position-absolute-iframe-child.html
fn css_position_resources_position_absolute_iframe_child() -> Document {
    let (mut doc, vp) = base_doc();
    doc.node_mut(vp).style.margin_top = Length::px(0.0);
    doc.node_mut(vp).style.margin_right = Length::px(0.0);
    doc.node_mut(vp).style.margin_bottom = Length::px(0.0);
    doc.node_mut(vp).style.margin_left = Length::px(0.0);
    let n1 = doc.create_node(ElementTag::Div);
    doc.node_mut(n1).style.display = Display::Block;
    doc.node_mut(n1).style.height = Length::px(1200.0);
    doc.append_child(vp, n1);
    let n2 = doc.create_node(ElementTag::Div);
    doc.node_mut(n2).style.display = Display::Block;
    doc.node_mut(n2).style.position = Position::Absolute;
    doc.node_mut(n2).style.top = Length::px(0.0);
    doc.node_mut(n2).style.left = Length::px(0.0);
    doc.append_child(vp, n2);
    doc
}

pub fn css_position_registry() -> Vec<(&'static str, fn() -> Document)> {
    vec![
        ("wpt/css_position/absolute-pos-box-inside-fixed-pos-box-with-changing-height-ref", css_position_absolute_pos_box_inside_fixed_pos_box_with_changing_height_ref as fn() -> Document),
        ("wpt/css_position/block-axis-constraint-changes-for-out-of-flow-box-ref", css_position_block_axis_constraint_changes_for_out_of_flow_box_ref as fn() -> Document),
        ("wpt/css_position/containing-block-change-scrollframe-ref", css_position_containing_block_change_scrollframe_ref as fn() -> Document),
        ("wpt/css_position/hypothetical-dynamic-change-001-ref", css_position_hypothetical_dynamic_change_001_ref as fn() -> Document),
        ("wpt/css_position/position-absolute-center-001", css_position_position_absolute_center_001 as fn() -> Document),
        ("wpt/css_position/position-absolute-center-003", css_position_position_absolute_center_003 as fn() -> Document),
        ("wpt/css_position/position-absolute-center-004", css_position_position_absolute_center_004 as fn() -> Document),
        ("wpt/css_position/position-absolute-fit-content", css_position_position_absolute_fit_content as fn() -> Document),
        ("wpt/css_position/position-absolute-iframe-print-ref", css_position_position_absolute_iframe_print_ref as fn() -> Document),
        ("wpt/css_position/position-absolute-in-inline-003", css_position_position_absolute_in_inline_003 as fn() -> Document),
        ("wpt/css_position/position-absolute-in-inline-004", css_position_position_absolute_in_inline_004 as fn() -> Document),
        ("wpt/css_position/position-absolute-large-negative-inset-ref", css_position_position_absolute_large_negative_inset_ref as fn() -> Document),
        ("wpt/css_position/position-absolute-multicol-001", css_position_position_absolute_multicol_001 as fn() -> Document),
        ("wpt/css_position/position-change-ref", css_position_position_change_ref as fn() -> Document),
        ("wpt/css_position/position-fixed-dynamic-transformed-sibling-ref", css_position_position_fixed_dynamic_transformed_sibling_ref as fn() -> Document),
        ("wpt/css_position/position-fixed-overflow-print-ref", css_position_position_fixed_overflow_print_ref as fn() -> Document),
        ("wpt/css_position/position-fixed-overflow-print", css_position_position_fixed_overflow_print as fn() -> Document),
        ("wpt/css_position/position-fixed-scroll-nested-fixed-ref", css_position_position_fixed_scroll_nested_fixed_ref as fn() -> Document),
        ("wpt/css_position/position-fixed-scroll-overlap-ref", css_position_position_fixed_scroll_overlap_ref as fn() -> Document),
        ("wpt/css_position/position-relative-001", css_position_position_relative_001 as fn() -> Document),
        ("wpt/css_position/position-relative-002", css_position_position_relative_002 as fn() -> Document),
        ("wpt/css_position/position-relative-003", css_position_position_relative_003 as fn() -> Document),
        ("wpt/css_position/position-relative-006", css_position_position_relative_006 as fn() -> Document),
        ("wpt/css_position/position-relative-007", css_position_position_relative_007 as fn() -> Document),
        ("wpt/css_position/static-position_htb-ref", css_position_static_position_htb_ref as fn() -> Document),
        ("wpt/css_position/static-position_inline-level-absolute-in-block-level-context-013", css_position_static_position_inline_level_absolute_in_block_level_context_013 as fn() -> Document),
        ("wpt/css_position/static-position_inline-level-absolute-in-block-level-context-014", css_position_static_position_inline_level_absolute_in_block_level_context_014 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-bottom-004", css_position_sticky_position_sticky_bottom_004 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-bottom-005", css_position_sticky_position_sticky_bottom_005 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-bottom-006", css_position_sticky_position_sticky_bottom_006 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-change-top-ref", css_position_sticky_position_sticky_change_top_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-column-reverse-flex-ref", css_position_sticky_position_sticky_column_reverse_flex_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-escape-scroller-001-ref", css_position_sticky_position_sticky_escape_scroller_001_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-fixed-ancestor-003", css_position_sticky_position_sticky_fixed_ancestor_003 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-margins-002", css_position_sticky_position_sticky_margins_002 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-margins-003", css_position_sticky_position_sticky_margins_003 as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-padding-001-ref", css_position_sticky_position_sticky_padding_001_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-padding-002-ref", css_position_sticky_position_sticky_padding_002_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-rtl-ref", css_position_sticky_position_sticky_rtl_ref as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-rtl", css_position_sticky_position_sticky_rtl as fn() -> Document),
        ("wpt/css_position/sticky_position-sticky-stacking-context-ref", css_position_sticky_position_sticky_stacking_context_ref as fn() -> Document),
        ("wpt/css_position/resources_position-absolute-iframe-child", css_position_resources_position_absolute_iframe_child as fn() -> Document),
    ]
}
