// @generated by tools/style/generate_properties.py; do not edit.

/// Stable property identifiers shared by Rust and the v0.2 C ABI.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StyleProperty {
    Display = 1,
    Position = 2,
    Overflow = 3,
    Width = 4,
    Height = 5,
    MinWidth = 6,
    MinHeight = 7,
    MaxWidth = 8,
    MaxHeight = 9,
    Margin = 10,
    MarginTop = 11,
    MarginRight = 12,
    MarginBottom = 13,
    MarginLeft = 14,
    Padding = 15,
    PaddingTop = 16,
    PaddingRight = 17,
    PaddingBottom = 18,
    PaddingLeft = 19,
    BackgroundColor = 20,
    Color = 21,
    Opacity = 22,
    ZIndex = 23,
    FlexDirection = 24,
    FlexWrap = 25,
    FlexGrow = 26,
    FlexShrink = 27,
    FlexBasis = 28,
    AlignItems = 29,
    JustifyContent = 30,
    Gap = 31,
    RowGap = 32,
    ColumnGap = 33,
    FontFamily = 34,
    FontSize = 35,
    FontWeight = 36,
    Border = 37,
    BorderTop = 38,
    BorderRight = 39,
    BorderBottom = 40,
    BorderLeft = 41,
    BorderRadius = 42,
    Cursor = 43,
    ListStyleType = 44,
    Transform = 45,
    PointerEvents = 46,
}

impl StyleProperty {
    /// Look up a schema property. This is intended for tooling and macro expansion;
    /// application mutation APIs accept `StyleProperty`, never a runtime name.
    pub fn from_css_name(name: &str) -> Option<Self> {
        match name {
            "display" => Some(Self::Display),
            "position" => Some(Self::Position),
            "overflow" => Some(Self::Overflow),
            "width" => Some(Self::Width),
            "height" => Some(Self::Height),
            "min-width" => Some(Self::MinWidth),
            "min-height" => Some(Self::MinHeight),
            "max-width" => Some(Self::MaxWidth),
            "max-height" => Some(Self::MaxHeight),
            "margin" => Some(Self::Margin),
            "margin-top" => Some(Self::MarginTop),
            "margin-right" => Some(Self::MarginRight),
            "margin-bottom" => Some(Self::MarginBottom),
            "margin-left" => Some(Self::MarginLeft),
            "padding" => Some(Self::Padding),
            "padding-top" => Some(Self::PaddingTop),
            "padding-right" => Some(Self::PaddingRight),
            "padding-bottom" => Some(Self::PaddingBottom),
            "padding-left" => Some(Self::PaddingLeft),
            "background-color" => Some(Self::BackgroundColor),
            "color" => Some(Self::Color),
            "opacity" => Some(Self::Opacity),
            "z-index" => Some(Self::ZIndex),
            "flex-direction" => Some(Self::FlexDirection),
            "flex-wrap" => Some(Self::FlexWrap),
            "flex-grow" => Some(Self::FlexGrow),
            "flex-shrink" => Some(Self::FlexShrink),
            "flex-basis" => Some(Self::FlexBasis),
            "align-items" => Some(Self::AlignItems),
            "justify-content" => Some(Self::JustifyContent),
            "gap" => Some(Self::Gap),
            "row-gap" => Some(Self::RowGap),
            "column-gap" => Some(Self::ColumnGap),
            "font-family" => Some(Self::FontFamily),
            "font-size" => Some(Self::FontSize),
            "font-weight" => Some(Self::FontWeight),
            "border" => Some(Self::Border),
            "border-top" => Some(Self::BorderTop),
            "border-right" => Some(Self::BorderRight),
            "border-bottom" => Some(Self::BorderBottom),
            "border-left" => Some(Self::BorderLeft),
            "border-radius" => Some(Self::BorderRadius),
            "cursor" => Some(Self::Cursor),
            "list-style" => Some(Self::ListStyleType),
            "transform" => Some(Self::Transform),
            "pointer-events" => Some(Self::PointerEvents),
            _ => None,
        }
    }

    pub fn metadata(self) -> &'static PropertyMetadata {
        &PROPERTY_METADATA[self as usize - 1]
    }
}

pub const PROPERTY_METADATA: &[PropertyMetadata] = &[
    PropertyMetadata {
        property: StyleProperty::Display,
        css_name: "display",
        rust_type: "Display",
        value_kind: ValueKind::Display,
        initial: "inline",
        inherited: false,
        invalidation: InvalidationClass::Subtree,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Position,
        css_name: "position",
        rust_type: "Position",
        value_kind: ValueKind::Position,
        initial: "static",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Overflow,
        css_name: "overflow",
        rust_type: "Overflow",
        value_kind: ValueKind::Overflow,
        initial: "visible",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Width,
        css_name: "width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Height,
        css_name: "height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MinWidth,
        css_name: "min-width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MinHeight,
        css_name: "min-height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MaxWidth,
        css_name: "max-width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MaxHeight,
        css_name: "max-height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Margin,
        css_name: "margin",
        rust_type: "Edges<LengthValue>",
        value_kind: ValueKind::Edges,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::MarginTop,
        css_name: "margin-top",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginRight,
        css_name: "margin-right",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginBottom,
        css_name: "margin-bottom",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginLeft,
        css_name: "margin-left",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Padding,
        css_name: "padding",
        rust_type: "Edges<LengthValue>",
        value_kind: ValueKind::Edges,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingTop,
        css_name: "padding-top",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingRight,
        css_name: "padding-right",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingBottom,
        css_name: "padding-bottom",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingLeft,
        css_name: "padding-left",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::BackgroundColor,
        css_name: "background-color",
        rust_type: "Color",
        value_kind: ValueKind::Color,
        initial: "transparent",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::Color,
        css_name: "color",
        rust_type: "Color",
        value_kind: ValueKind::Color,
        initial: "black",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::Opacity,
        css_name: "opacity",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "1",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::ZIndex,
        css_name: "z-index",
        rust_type: "i32",
        value_kind: ValueKind::Integer,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Integer,
    },
    PropertyMetadata {
        property: StyleProperty::FlexDirection,
        css_name: "flex-direction",
        rust_type: "FlexDirection",
        value_kind: ValueKind::FlexDirection,
        initial: "row",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FlexWrap,
        css_name: "flex-wrap",
        rust_type: "FlexWrap",
        value_kind: ValueKind::FlexWrap,
        initial: "nowrap",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FlexGrow,
        css_name: "flex-grow",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "0",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FlexShrink,
        css_name: "flex-shrink",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "1",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FlexBasis,
        css_name: "flex-basis",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::AlignItems,
        css_name: "align-items",
        rust_type: "ItemAlignment",
        value_kind: ValueKind::ItemAlignment,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::JustifyContent,
        css_name: "justify-content",
        rust_type: "ContentAlignment",
        value_kind: ValueKind::ContentAlignment,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Gap,
        css_name: "gap",
        rust_type: "Gap",
        value_kind: ValueKind::Gap,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::RowGap,
        css_name: "row-gap",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::ColumnGap,
        css_name: "column-gap",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::FontFamily,
        css_name: "font-family",
        rust_type: "FontFamilyList",
        value_kind: ValueKind::FontFamily,
        initial: "sans-serif",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSize,
        css_name: "font-size",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "16px",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::FontWeight,
        css_name: "font-weight",
        rust_type: "FontWeight",
        value_kind: ValueKind::FontWeight,
        initial: "400",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::Border,
        css_name: "border",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderTop,
        css_name: "border-top",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderRight,
        css_name: "border-right",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderBottom,
        css_name: "border-bottom",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderLeft,
        css_name: "border-left",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderRadius,
        css_name: "border-radius",
        rust_type: "CornerRadii",
        value_kind: ValueKind::CornerRadii,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::Cursor,
        css_name: "cursor",
        rust_type: "Cursor",
        value_kind: ValueKind::Cursor,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Accessibility,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::ListStyleType,
        css_name: "list-style",
        rust_type: "ListStyleType",
        value_kind: ValueKind::ListStyle,
        initial: "disc",
        inherited: true,
        invalidation: InvalidationClass::Subtree,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Transform,
        css_name: "transform",
        rust_type: "TransformList",
        value_kind: ValueKind::Transform,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Transform,
    },
    PropertyMetadata {
        property: StyleProperty::PointerEvents,
        css_name: "pointer-events",
        rust_type: "PointerEvents",
        value_kind: ValueKind::PointerEvents,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Accessibility,
        interpolation: InterpolationKind::Discrete,
    },
];

#[rustfmt::skip]
impl Style {
    pub fn display(self, value: Display) -> Self {
        self.with(StyleProperty::Display, value)
    }
    pub fn position(self, value: Position) -> Self {
        self.with(StyleProperty::Position, value)
    }
    pub fn overflow(self, value: Overflow) -> Self {
        self.with(StyleProperty::Overflow, value)
    }
    pub fn width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::Width, value)
    }
    pub fn height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::Height, value)
    }
    pub fn min_width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MinWidth, value)
    }
    pub fn min_height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MinHeight, value)
    }
    pub fn max_width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MaxWidth, value)
    }
    pub fn max_height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MaxHeight, value)
    }
    pub fn margin(self, value: Edges<LengthValue>) -> Self {
        self.with(StyleProperty::Margin, value)
    }
    pub fn margin_top(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginTop, value)
    }
    pub fn margin_right(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginRight, value)
    }
    pub fn margin_bottom(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginBottom, value)
    }
    pub fn margin_left(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginLeft, value)
    }
    pub fn padding(self, value: Edges<LengthValue>) -> Self {
        self.with(StyleProperty::Padding, value)
    }
    pub fn padding_top(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingTop, value)
    }
    pub fn padding_right(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingRight, value)
    }
    pub fn padding_bottom(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingBottom, value)
    }
    pub fn padding_left(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingLeft, value)
    }
    pub fn background_color(self, value: Color) -> Self {
        self.with(StyleProperty::BackgroundColor, value)
    }
    pub fn color(self, value: Color) -> Self {
        self.with(StyleProperty::Color, value)
    }
    pub fn opacity(self, value: f32) -> Self {
        self.with(StyleProperty::Opacity, value)
    }
    pub fn z_index(self, value: i32) -> Self {
        self.with(StyleProperty::ZIndex, value)
    }
    pub fn flex_direction(self, value: FlexDirection) -> Self {
        self.with(StyleProperty::FlexDirection, value)
    }
    pub fn flex_wrap(self, value: FlexWrap) -> Self {
        self.with(StyleProperty::FlexWrap, value)
    }
    pub fn flex_grow(self, value: f32) -> Self {
        self.with(StyleProperty::FlexGrow, value)
    }
    pub fn flex_shrink(self, value: f32) -> Self {
        self.with(StyleProperty::FlexShrink, value)
    }
    pub fn flex_basis(self, value: LengthValue) -> Self {
        self.with(StyleProperty::FlexBasis, value)
    }
    pub fn align_items(self, value: ItemAlignment) -> Self {
        self.with(StyleProperty::AlignItems, value)
    }
    pub fn justify_content(self, value: ContentAlignment) -> Self {
        self.with(StyleProperty::JustifyContent, value)
    }
    pub fn gap(self, value: Gap) -> Self {
        self.with(StyleProperty::Gap, value)
    }
    pub fn row_gap(self, value: LengthValue) -> Self {
        self.with(StyleProperty::RowGap, value)
    }
    pub fn column_gap(self, value: LengthValue) -> Self {
        self.with(StyleProperty::ColumnGap, value)
    }
    pub fn font_family(self, value: FontFamilyList) -> Self {
        self.with(StyleProperty::FontFamily, value)
    }
    pub fn font_size(self, value: LengthValue) -> Self {
        self.with(StyleProperty::FontSize, value)
    }
    pub fn font_weight(self, value: FontWeight) -> Self {
        self.with(StyleProperty::FontWeight, value)
    }
    pub fn border(self, value: Border) -> Self {
        self.with(StyleProperty::Border, value)
    }
    pub fn border_top(self, value: Border) -> Self {
        self.with(StyleProperty::BorderTop, value)
    }
    pub fn border_right(self, value: Border) -> Self {
        self.with(StyleProperty::BorderRight, value)
    }
    pub fn border_bottom(self, value: Border) -> Self {
        self.with(StyleProperty::BorderBottom, value)
    }
    pub fn border_left(self, value: Border) -> Self {
        self.with(StyleProperty::BorderLeft, value)
    }
    pub fn border_radius(self, value: CornerRadii) -> Self {
        self.with(StyleProperty::BorderRadius, value)
    }
    pub fn cursor(self, value: Cursor) -> Self {
        self.with(StyleProperty::Cursor, value)
    }
    pub fn list_style(self, value: ListStyleType) -> Self {
        self.with(StyleProperty::ListStyleType, value)
    }
    pub fn transform(self, value: TransformList) -> Self {
        self.with(StyleProperty::Transform, value)
    }
    pub fn pointer_events(self, value: PointerEvents) -> Self {
        self.with(StyleProperty::PointerEvents, value)
    }
}
