// @generated by tools/style/generate_properties.py; do not edit.

/// Stable property identifiers shared by Rust and the v0.2 C ABI.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StyleProperty {
    Display = 1,
    Position = 2,
    Overflow = 3,
    Width = 4,
    Height = 5,
    MinWidth = 6,
    MinHeight = 7,
    MaxWidth = 8,
    MaxHeight = 9,
    Margin = 10,
    MarginTop = 11,
    MarginRight = 12,
    MarginBottom = 13,
    MarginLeft = 14,
    Padding = 15,
    PaddingTop = 16,
    PaddingRight = 17,
    PaddingBottom = 18,
    PaddingLeft = 19,
    BackgroundColor = 20,
    Color = 21,
    Opacity = 22,
    ZIndex = 23,
    FlexDirection = 24,
    FlexWrap = 25,
    FlexGrow = 26,
    FlexShrink = 27,
    FlexBasis = 28,
    AlignItems = 29,
    JustifyContent = 30,
    Gap = 31,
    RowGap = 32,
    ColumnGap = 33,
    FontFamily = 34,
    FontSize = 35,
    FontWeight = 36,
    Border = 37,
    BorderTop = 38,
    BorderRight = 39,
    BorderBottom = 40,
    BorderLeft = 41,
    BorderRadius = 42,
    Cursor = 43,
    ListStyleType = 44,
    Transform = 45,
    PointerEvents = 46,
    Direction = 47,
    FontKerning = 48,
    FontOpticalSizing = 49,
    FontPalette = 50,
    FontSizeAdjust = 51,
    FontStretch = 52,
    FontStyle = 53,
    FontVariantLigatures = 54,
    FontVariantCaps = 55,
    FontVariantEastAsian = 56,
    FontVariantNumeric = 57,
    FontVariantAlternates = 58,
    FontVariantPosition = 59,
    FontVariantEmoji = 60,
    FontSynthesisWeight = 61,
    FontSynthesisStyle = 62,
    FontSynthesisSmallCaps = 63,
    FontSynthesisPosition = 64,
    FontFeatureSettings = 65,
    FontVariationSettings = 66,
    FontLanguageOverride = 67,
    LineHeight = 68,
    LetterSpacing = 69,
    WordSpacing = 70,
    TextIndent = 71,
    TextAlign = 72,
    TextAlignLast = 73,
    TextJustify = 74,
    WordBreak = 75,
    OverflowWrap = 76,
    WordWrap = 77,
    LineBreak = 78,
    Hyphens = 79,
    HyphenateLimitChars = 80,
    HyphenateCharacter = 81,
    WhiteSpaceCollapse = 82,
    TextWrapMode = 83,
    TextWrapStyle = 84,
    TextAutospace = 85,
    TextSpacingTrim = 86,
    TabSize = 87,
    TextTransform = 88,
    TextDecorationLine = 89,
    TextDecorationStyle = 90,
    TextDecorationColor = 91,
    TextDecorationThickness = 92,
    TextDecorationSkipInk = 93,
    TextUnderlineOffset = 94,
    TextUnderlinePosition = 95,
    TextEmphasisStyle = 96,
    TextEmphasisPosition = 97,
    TextEmphasisColor = 98,
    TextShadow = 99,
    TextOverflow = 100,
    TextSizeAdjust = 101,
    TextCombineUpright = 102,
    WritingMode = 103,
    TextOrientation = 104,
    UnicodeBidi = 105,
    VerticalAlign = 106,
    RubyAlign = 107,
    RubyPosition = 108,
    RubyOverhang = 109,
    HangingPunctuation = 110,
    InitialLetter = 111,
    TextRendering = 112,
    WebkitFontSmoothing = 113,
    LineClamp = 114,
    BlockEllipsis = 115,
    TextBoxEdge = 116,
    TextBoxTrim = 117,
    Font = 118,
    FontVariant = 119,
    FontSynthesis = 120,
    WhiteSpace = 121,
    TextWrap = 122,
    TextDecoration = 123,
    TextEmphasis = 124,
    TextBox = 125,
}

impl StyleProperty {
    pub fn from_u16(value: u16) -> Option<Self> {
        PROPERTY_METADATA
            .get(value.checked_sub(1)? as usize)
            .map(|metadata| metadata.property)
    }

    /// Look up a schema property. This is intended for tooling and macro expansion;
    /// application mutation APIs accept `StyleProperty`, never a runtime name.
    pub fn from_css_name(name: &str) -> Option<Self> {
        match name {
            "display" => Some(Self::Display),
            "position" => Some(Self::Position),
            "overflow" => Some(Self::Overflow),
            "width" => Some(Self::Width),
            "height" => Some(Self::Height),
            "min-width" => Some(Self::MinWidth),
            "min-height" => Some(Self::MinHeight),
            "max-width" => Some(Self::MaxWidth),
            "max-height" => Some(Self::MaxHeight),
            "margin" => Some(Self::Margin),
            "margin-top" => Some(Self::MarginTop),
            "margin-right" => Some(Self::MarginRight),
            "margin-bottom" => Some(Self::MarginBottom),
            "margin-left" => Some(Self::MarginLeft),
            "padding" => Some(Self::Padding),
            "padding-top" => Some(Self::PaddingTop),
            "padding-right" => Some(Self::PaddingRight),
            "padding-bottom" => Some(Self::PaddingBottom),
            "padding-left" => Some(Self::PaddingLeft),
            "background-color" => Some(Self::BackgroundColor),
            "color" => Some(Self::Color),
            "opacity" => Some(Self::Opacity),
            "z-index" => Some(Self::ZIndex),
            "flex-direction" => Some(Self::FlexDirection),
            "flex-wrap" => Some(Self::FlexWrap),
            "flex-grow" => Some(Self::FlexGrow),
            "flex-shrink" => Some(Self::FlexShrink),
            "flex-basis" => Some(Self::FlexBasis),
            "align-items" => Some(Self::AlignItems),
            "justify-content" => Some(Self::JustifyContent),
            "gap" => Some(Self::Gap),
            "row-gap" => Some(Self::RowGap),
            "column-gap" => Some(Self::ColumnGap),
            "font-family" => Some(Self::FontFamily),
            "font-size" => Some(Self::FontSize),
            "font-weight" => Some(Self::FontWeight),
            "border" => Some(Self::Border),
            "border-top" => Some(Self::BorderTop),
            "border-right" => Some(Self::BorderRight),
            "border-bottom" => Some(Self::BorderBottom),
            "border-left" => Some(Self::BorderLeft),
            "border-radius" => Some(Self::BorderRadius),
            "cursor" => Some(Self::Cursor),
            "list-style" => Some(Self::ListStyleType),
            "transform" => Some(Self::Transform),
            "pointer-events" => Some(Self::PointerEvents),
            "direction" => Some(Self::Direction),
            "font-kerning" => Some(Self::FontKerning),
            "font-optical-sizing" => Some(Self::FontOpticalSizing),
            "font-palette" => Some(Self::FontPalette),
            "font-size-adjust" => Some(Self::FontSizeAdjust),
            "font-stretch" => Some(Self::FontStretch),
            "font-style" => Some(Self::FontStyle),
            "font-variant-ligatures" => Some(Self::FontVariantLigatures),
            "font-variant-caps" => Some(Self::FontVariantCaps),
            "font-variant-east-asian" => Some(Self::FontVariantEastAsian),
            "font-variant-numeric" => Some(Self::FontVariantNumeric),
            "font-variant-alternates" => Some(Self::FontVariantAlternates),
            "font-variant-position" => Some(Self::FontVariantPosition),
            "font-variant-emoji" => Some(Self::FontVariantEmoji),
            "font-synthesis-weight" => Some(Self::FontSynthesisWeight),
            "font-synthesis-style" => Some(Self::FontSynthesisStyle),
            "font-synthesis-small-caps" => Some(Self::FontSynthesisSmallCaps),
            "font-synthesis-position" => Some(Self::FontSynthesisPosition),
            "font-feature-settings" => Some(Self::FontFeatureSettings),
            "font-variation-settings" => Some(Self::FontVariationSettings),
            "font-language-override" => Some(Self::FontLanguageOverride),
            "line-height" => Some(Self::LineHeight),
            "letter-spacing" => Some(Self::LetterSpacing),
            "word-spacing" => Some(Self::WordSpacing),
            "text-indent" => Some(Self::TextIndent),
            "text-align" => Some(Self::TextAlign),
            "text-align-last" => Some(Self::TextAlignLast),
            "text-justify" => Some(Self::TextJustify),
            "word-break" => Some(Self::WordBreak),
            "overflow-wrap" => Some(Self::OverflowWrap),
            "word-wrap" => Some(Self::WordWrap),
            "line-break" => Some(Self::LineBreak),
            "hyphens" => Some(Self::Hyphens),
            "hyphenate-limit-chars" => Some(Self::HyphenateLimitChars),
            "hyphenate-character" => Some(Self::HyphenateCharacter),
            "white-space-collapse" => Some(Self::WhiteSpaceCollapse),
            "text-wrap-mode" => Some(Self::TextWrapMode),
            "text-wrap-style" => Some(Self::TextWrapStyle),
            "text-autospace" => Some(Self::TextAutospace),
            "text-spacing-trim" => Some(Self::TextSpacingTrim),
            "tab-size" => Some(Self::TabSize),
            "text-transform" => Some(Self::TextTransform),
            "text-decoration-line" => Some(Self::TextDecorationLine),
            "text-decoration-style" => Some(Self::TextDecorationStyle),
            "text-decoration-color" => Some(Self::TextDecorationColor),
            "text-decoration-thickness" => Some(Self::TextDecorationThickness),
            "text-decoration-skip-ink" => Some(Self::TextDecorationSkipInk),
            "text-underline-offset" => Some(Self::TextUnderlineOffset),
            "text-underline-position" => Some(Self::TextUnderlinePosition),
            "text-emphasis-style" => Some(Self::TextEmphasisStyle),
            "text-emphasis-position" => Some(Self::TextEmphasisPosition),
            "text-emphasis-color" => Some(Self::TextEmphasisColor),
            "text-shadow" => Some(Self::TextShadow),
            "text-overflow" => Some(Self::TextOverflow),
            "text-size-adjust" => Some(Self::TextSizeAdjust),
            "text-combine-upright" => Some(Self::TextCombineUpright),
            "writing-mode" => Some(Self::WritingMode),
            "text-orientation" => Some(Self::TextOrientation),
            "unicode-bidi" => Some(Self::UnicodeBidi),
            "vertical-align" => Some(Self::VerticalAlign),
            "ruby-align" => Some(Self::RubyAlign),
            "ruby-position" => Some(Self::RubyPosition),
            "ruby-overhang" => Some(Self::RubyOverhang),
            "hanging-punctuation" => Some(Self::HangingPunctuation),
            "initial-letter" => Some(Self::InitialLetter),
            "text-rendering" => Some(Self::TextRendering),
            "-webkit-font-smoothing" => Some(Self::WebkitFontSmoothing),
            "line-clamp" => Some(Self::LineClamp),
            "block-ellipsis" => Some(Self::BlockEllipsis),
            "text-box-edge" => Some(Self::TextBoxEdge),
            "text-box-trim" => Some(Self::TextBoxTrim),
            "font" => Some(Self::Font),
            "font-variant" => Some(Self::FontVariant),
            "font-synthesis" => Some(Self::FontSynthesis),
            "white-space" => Some(Self::WhiteSpace),
            "text-wrap" => Some(Self::TextWrap),
            "text-decoration" => Some(Self::TextDecoration),
            "text-emphasis" => Some(Self::TextEmphasis),
            "text-box" => Some(Self::TextBox),
            _ => None,
        }
    }

    pub fn metadata(self) -> &'static PropertyMetadata {
        &PROPERTY_METADATA[self as usize - 1]
    }
}

pub const PROPERTY_METADATA: &[PropertyMetadata] = &[
    PropertyMetadata {
        property: StyleProperty::Display,
        css_name: "display",
        rust_type: "Display",
        value_kind: ValueKind::Display,
        initial: "inline",
        inherited: false,
        invalidation: InvalidationClass::Subtree,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Position,
        css_name: "position",
        rust_type: "Position",
        value_kind: ValueKind::Position,
        initial: "static",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Overflow,
        css_name: "overflow",
        rust_type: "Overflow",
        value_kind: ValueKind::Overflow,
        initial: "visible",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Width,
        css_name: "width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Height,
        css_name: "height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MinWidth,
        css_name: "min-width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MinHeight,
        css_name: "min-height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MaxWidth,
        css_name: "max-width",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MaxHeight,
        css_name: "max-height",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Margin,
        css_name: "margin",
        rust_type: "Edges<LengthValue>",
        value_kind: ValueKind::Edges,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::MarginTop,
        css_name: "margin-top",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginRight,
        css_name: "margin-right",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginBottom,
        css_name: "margin-bottom",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::MarginLeft,
        css_name: "margin-left",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::Padding,
        css_name: "padding",
        rust_type: "Edges<LengthValue>",
        value_kind: ValueKind::Edges,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingTop,
        css_name: "padding-top",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingRight,
        css_name: "padding-right",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingBottom,
        css_name: "padding-bottom",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::PaddingLeft,
        css_name: "padding-left",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::BackgroundColor,
        css_name: "background-color",
        rust_type: "Color",
        value_kind: ValueKind::Color,
        initial: "transparent",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::Color,
        css_name: "color",
        rust_type: "Color",
        value_kind: ValueKind::Color,
        initial: "black",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::Opacity,
        css_name: "opacity",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "1",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::ZIndex,
        css_name: "z-index",
        rust_type: "i32",
        value_kind: ValueKind::Integer,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Integer,
    },
    PropertyMetadata {
        property: StyleProperty::FlexDirection,
        css_name: "flex-direction",
        rust_type: "FlexDirection",
        value_kind: ValueKind::FlexDirection,
        initial: "row",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FlexWrap,
        css_name: "flex-wrap",
        rust_type: "FlexWrap",
        value_kind: ValueKind::FlexWrap,
        initial: "nowrap",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FlexGrow,
        css_name: "flex-grow",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "0",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FlexShrink,
        css_name: "flex-shrink",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "1",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FlexBasis,
        css_name: "flex-basis",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::AlignItems,
        css_name: "align-items",
        rust_type: "ItemAlignment",
        value_kind: ValueKind::ItemAlignment,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::JustifyContent,
        css_name: "justify-content",
        rust_type: "ContentAlignment",
        value_kind: ValueKind::ContentAlignment,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Gap,
        css_name: "gap",
        rust_type: "Gap",
        value_kind: ValueKind::Gap,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::RowGap,
        css_name: "row-gap",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::ColumnGap,
        css_name: "column-gap",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::FontFamily,
        css_name: "font-family",
        rust_type: "FontFamilyList",
        value_kind: ValueKind::FontFamily,
        initial: "sans-serif",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSize,
        css_name: "font-size",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "16px",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::FontWeight,
        css_name: "font-weight",
        rust_type: "FontWeight",
        value_kind: ValueKind::FontWeight,
        initial: "400",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::Border,
        css_name: "border",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderTop,
        css_name: "border-top",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderRight,
        css_name: "border-right",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderBottom,
        css_name: "border-bottom",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderLeft,
        css_name: "border-left",
        rust_type: "Border",
        value_kind: ValueKind::Border,
        initial: "medium none currentColor",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BorderRadius,
        css_name: "border-radius",
        rust_type: "CornerRadii",
        value_kind: ValueKind::CornerRadii,
        initial: "0px",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::LengthList,
    },
    PropertyMetadata {
        property: StyleProperty::Cursor,
        css_name: "cursor",
        rust_type: "Cursor",
        value_kind: ValueKind::Cursor,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Accessibility,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::ListStyleType,
        css_name: "list-style",
        rust_type: "ListStyleType",
        value_kind: ValueKind::ListStyle,
        initial: "disc",
        inherited: true,
        invalidation: InvalidationClass::Subtree,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Transform,
        css_name: "transform",
        rust_type: "TransformList",
        value_kind: ValueKind::Transform,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Composite,
        interpolation: InterpolationKind::Transform,
    },
    PropertyMetadata {
        property: StyleProperty::PointerEvents,
        css_name: "pointer-events",
        rust_type: "PointerEvents",
        value_kind: ValueKind::PointerEvents,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Accessibility,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Direction,
        css_name: "direction",
        rust_type: "Direction",
        value_kind: ValueKind::Enum,
        initial: "ltr",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontKerning,
        css_name: "font-kerning",
        rust_type: "FontKerning",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontOpticalSizing,
        css_name: "font-optical-sizing",
        rust_type: "FontOpticalSizing",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontPalette,
        css_name: "font-palette",
        rust_type: "FontPalette",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSizeAdjust,
        css_name: "font-size-adjust",
        rust_type: "FontSizeAdjust",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FontStretch,
        css_name: "font-stretch",
        rust_type: "FontStretch",
        value_kind: ValueKind::Compound,
        initial: "100%",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::FontStyle,
        css_name: "font-style",
        rust_type: "FontStyleEnum",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantLigatures,
        css_name: "font-variant-ligatures",
        rust_type: "FontVariantLigatures",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantCaps,
        css_name: "font-variant-caps",
        rust_type: "FontVariantCaps",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantEastAsian,
        css_name: "font-variant-east-asian",
        rust_type: "FontVariantEastAsian",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantNumeric,
        css_name: "font-variant-numeric",
        rust_type: "FontVariantNumeric",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantAlternates,
        css_name: "font-variant-alternates",
        rust_type: "FontVariantAlternates",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantPosition,
        css_name: "font-variant-position",
        rust_type: "FontVariantPosition",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariantEmoji,
        css_name: "font-variant-emoji",
        rust_type: "FontVariantEmoji",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSynthesisWeight,
        css_name: "font-synthesis-weight",
        rust_type: "FontSynthesis",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSynthesisStyle,
        css_name: "font-synthesis-style",
        rust_type: "FontSynthesis",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSynthesisSmallCaps,
        css_name: "font-synthesis-small-caps",
        rust_type: "FontSynthesis",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSynthesisPosition,
        css_name: "font-synthesis-position",
        rust_type: "FontSynthesis",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontFeatureSettings,
        css_name: "font-feature-settings",
        rust_type: "OpenTypeFeatureList",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariationSettings,
        css_name: "font-variation-settings",
        rust_type: "FontVariationList",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontLanguageOverride,
        css_name: "font-language-override",
        rust_type: "FontLanguageOverride",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::LineHeight,
        css_name: "line-height",
        rust_type: "LineHeight",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::LetterSpacing,
        css_name: "letter-spacing",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::WordSpacing,
        css_name: "word-spacing",
        rust_type: "f32",
        value_kind: ValueKind::Number,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::TextIndent,
        css_name: "text-indent",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "0px",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::TextAlign,
        css_name: "text-align",
        rust_type: "TextAlign",
        value_kind: ValueKind::Enum,
        initial: "start",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextAlignLast,
        css_name: "text-align-last",
        rust_type: "TextAlignLast",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextJustify,
        css_name: "text-justify",
        rust_type: "TextJustify",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WordBreak,
        css_name: "word-break",
        rust_type: "WordBreak",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::OverflowWrap,
        css_name: "overflow-wrap",
        rust_type: "OverflowWrap",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WordWrap,
        css_name: "word-wrap",
        rust_type: "OverflowWrap",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::LineBreak,
        css_name: "line-break",
        rust_type: "LineBreak",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Hyphens,
        css_name: "hyphens",
        rust_type: "Hyphens",
        value_kind: ValueKind::Enum,
        initial: "manual",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::HyphenateLimitChars,
        css_name: "hyphenate-limit-chars",
        rust_type: "HyphenationLimits",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::HyphenateCharacter,
        css_name: "hyphenate-character",
        rust_type: "HyphenateCharacter",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WhiteSpaceCollapse,
        css_name: "white-space-collapse",
        rust_type: "WhiteSpaceCollapse",
        value_kind: ValueKind::Enum,
        initial: "collapse",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextWrapMode,
        css_name: "text-wrap-mode",
        rust_type: "TextWrapMode",
        value_kind: ValueKind::Enum,
        initial: "wrap",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextWrapStyle,
        css_name: "text-wrap-style",
        rust_type: "TextWrapStyle",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextAutospace,
        css_name: "text-autospace",
        rust_type: "TextAutospace",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextSpacingTrim,
        css_name: "text-spacing-trim",
        rust_type: "TextSpacingTrim",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TabSize,
        css_name: "tab-size",
        rust_type: "TabSize",
        value_kind: ValueKind::Compound,
        initial: "8",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::TextTransform,
        css_name: "text-transform",
        rust_type: "TextTransform",
        value_kind: ValueKind::Enum,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecorationLine,
        css_name: "text-decoration-line",
        rust_type: "TextDecorationLine",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecorationStyle,
        css_name: "text-decoration-style",
        rust_type: "TextDecorationStyle",
        value_kind: ValueKind::Enum,
        initial: "solid",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecorationColor,
        css_name: "text-decoration-color",
        rust_type: "StyleColor",
        value_kind: ValueKind::Compound,
        initial: "currentColor",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecorationThickness,
        css_name: "text-decoration-thickness",
        rust_type: "TextDecorationThickness",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecorationSkipInk,
        css_name: "text-decoration-skip-ink",
        rust_type: "TextDecorationSkipInk",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextUnderlineOffset,
        css_name: "text-underline-offset",
        rust_type: "LengthValue",
        value_kind: ValueKind::Length,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Length,
    },
    PropertyMetadata {
        property: StyleProperty::TextUnderlinePosition,
        css_name: "text-underline-position",
        rust_type: "TextUnderlinePosition",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextEmphasisStyle,
        css_name: "text-emphasis-style",
        rust_type: "TextEmphasisStyle",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextEmphasisPosition,
        css_name: "text-emphasis-position",
        rust_type: "TextEmphasisPosition",
        value_kind: ValueKind::Compound,
        initial: "over right",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextEmphasisColor,
        css_name: "text-emphasis-color",
        rust_type: "StyleColor",
        value_kind: ValueKind::Compound,
        initial: "currentColor",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Color,
    },
    PropertyMetadata {
        property: StyleProperty::TextShadow,
        css_name: "text-shadow",
        rust_type: "TextShadowList",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextOverflow,
        css_name: "text-overflow",
        rust_type: "TextOverflow",
        value_kind: ValueKind::Enum,
        initial: "clip",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextSizeAdjust,
        css_name: "text-size-adjust",
        rust_type: "TextSizeAdjust",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::TextCombineUpright,
        css_name: "text-combine-upright",
        rust_type: "TextCombineUpright",
        value_kind: ValueKind::Enum,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WritingMode,
        css_name: "writing-mode",
        rust_type: "WritingMode",
        value_kind: ValueKind::Enum,
        initial: "horizontal-tb",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextOrientation,
        css_name: "text-orientation",
        rust_type: "TextOrientation",
        value_kind: ValueKind::Enum,
        initial: "mixed",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::UnicodeBidi,
        css_name: "unicode-bidi",
        rust_type: "UnicodeBidi",
        value_kind: ValueKind::Enum,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::VerticalAlign,
        css_name: "vertical-align",
        rust_type: "VerticalAlign",
        value_kind: ValueKind::Compound,
        initial: "baseline",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::RubyAlign,
        css_name: "ruby-align",
        rust_type: "RubyAlign",
        value_kind: ValueKind::Enum,
        initial: "space-around",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::RubyPosition,
        css_name: "ruby-position",
        rust_type: "RubyPosition",
        value_kind: ValueKind::Enum,
        initial: "over",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::RubyOverhang,
        css_name: "ruby-overhang",
        rust_type: "RubyOverhang",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::HangingPunctuation,
        css_name: "hanging-punctuation",
        rust_type: "HangingPunctuation",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::InitialLetter,
        css_name: "initial-letter",
        rust_type: "InitialLetterValue",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Number,
    },
    PropertyMetadata {
        property: StyleProperty::TextRendering,
        css_name: "text-rendering",
        rust_type: "TextRendering",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WebkitFontSmoothing,
        css_name: "-webkit-font-smoothing",
        rust_type: "FontSmoothing",
        value_kind: ValueKind::Enum,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::LineClamp,
        css_name: "line-clamp",
        rust_type: "LineClamp",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::BlockEllipsis,
        css_name: "block-ellipsis",
        rust_type: "BlockEllipsis",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextBoxEdge,
        css_name: "text-box-edge",
        rust_type: "TextBoxEdge",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextBoxTrim,
        css_name: "text-box-trim",
        rust_type: "TextBoxTrim",
        value_kind: ValueKind::Enum,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::Font,
        css_name: "font",
        rust_type: "FontShorthand",
        value_kind: ValueKind::Compound,
        initial: "medium sans-serif",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontVariant,
        css_name: "font-variant",
        rust_type: "FontVariantShorthand",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::FontSynthesis,
        css_name: "font-synthesis",
        rust_type: "FontSynthesisShorthand",
        value_kind: ValueKind::Compound,
        initial: "auto",
        inherited: true,
        invalidation: InvalidationClass::Intrinsic,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::WhiteSpace,
        css_name: "white-space",
        rust_type: "WhiteSpaceShorthand",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextWrap,
        css_name: "text-wrap",
        rust_type: "TextWrapShorthand",
        value_kind: ValueKind::Compound,
        initial: "wrap",
        inherited: true,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextDecoration,
        css_name: "text-decoration",
        rust_type: "TextDecorationShorthand",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: false,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextEmphasis,
        css_name: "text-emphasis",
        rust_type: "TextEmphasisShorthand",
        value_kind: ValueKind::Compound,
        initial: "none",
        inherited: true,
        invalidation: InvalidationClass::Paint,
        interpolation: InterpolationKind::Discrete,
    },
    PropertyMetadata {
        property: StyleProperty::TextBox,
        css_name: "text-box",
        rust_type: "TextBoxShorthand",
        value_kind: ValueKind::Compound,
        initial: "normal",
        inherited: false,
        invalidation: InvalidationClass::Layout,
        interpolation: InterpolationKind::Discrete,
    },
];

#[rustfmt::skip]
impl Style {
    pub fn display(self, value: Display) -> Self {
        self.with(StyleProperty::Display, value)
    }
    pub fn position(self, value: Position) -> Self {
        self.with(StyleProperty::Position, value)
    }
    pub fn overflow(self, value: Overflow) -> Self {
        self.with(StyleProperty::Overflow, value)
    }
    pub fn width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::Width, value)
    }
    pub fn height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::Height, value)
    }
    pub fn min_width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MinWidth, value)
    }
    pub fn min_height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MinHeight, value)
    }
    pub fn max_width(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MaxWidth, value)
    }
    pub fn max_height(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MaxHeight, value)
    }
    pub fn margin(self, value: Edges<LengthValue>) -> Self {
        self.with(StyleProperty::Margin, value)
    }
    pub fn margin_top(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginTop, value)
    }
    pub fn margin_right(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginRight, value)
    }
    pub fn margin_bottom(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginBottom, value)
    }
    pub fn margin_left(self, value: LengthValue) -> Self {
        self.with(StyleProperty::MarginLeft, value)
    }
    pub fn padding(self, value: Edges<LengthValue>) -> Self {
        self.with(StyleProperty::Padding, value)
    }
    pub fn padding_top(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingTop, value)
    }
    pub fn padding_right(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingRight, value)
    }
    pub fn padding_bottom(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingBottom, value)
    }
    pub fn padding_left(self, value: LengthValue) -> Self {
        self.with(StyleProperty::PaddingLeft, value)
    }
    pub fn background_color(self, value: Color) -> Self {
        self.with(StyleProperty::BackgroundColor, value)
    }
    pub fn color(self, value: Color) -> Self {
        self.with(StyleProperty::Color, value)
    }
    pub fn opacity(self, value: f32) -> Self {
        self.with(StyleProperty::Opacity, value)
    }
    pub fn z_index(self, value: i32) -> Self {
        self.with(StyleProperty::ZIndex, value)
    }
    pub fn flex_direction(self, value: FlexDirection) -> Self {
        self.with(StyleProperty::FlexDirection, value)
    }
    pub fn flex_wrap(self, value: FlexWrap) -> Self {
        self.with(StyleProperty::FlexWrap, value)
    }
    pub fn flex_grow(self, value: f32) -> Self {
        self.with(StyleProperty::FlexGrow, value)
    }
    pub fn flex_shrink(self, value: f32) -> Self {
        self.with(StyleProperty::FlexShrink, value)
    }
    pub fn flex_basis(self, value: LengthValue) -> Self {
        self.with(StyleProperty::FlexBasis, value)
    }
    pub fn align_items(self, value: ItemAlignment) -> Self {
        self.with(StyleProperty::AlignItems, value)
    }
    pub fn justify_content(self, value: ContentAlignment) -> Self {
        self.with(StyleProperty::JustifyContent, value)
    }
    pub fn gap(self, value: Gap) -> Self {
        self.with(StyleProperty::Gap, value)
    }
    pub fn row_gap(self, value: LengthValue) -> Self {
        self.with(StyleProperty::RowGap, value)
    }
    pub fn column_gap(self, value: LengthValue) -> Self {
        self.with(StyleProperty::ColumnGap, value)
    }
    pub fn font_family(self, value: FontFamilyList) -> Self {
        self.with(StyleProperty::FontFamily, value)
    }
    pub fn font_size(self, value: LengthValue) -> Self {
        self.with(StyleProperty::FontSize, value)
    }
    pub fn font_weight(self, value: FontWeight) -> Self {
        self.with(StyleProperty::FontWeight, value)
    }
    pub fn border(self, value: Border) -> Self {
        self.with(StyleProperty::Border, value)
    }
    pub fn border_top(self, value: Border) -> Self {
        self.with(StyleProperty::BorderTop, value)
    }
    pub fn border_right(self, value: Border) -> Self {
        self.with(StyleProperty::BorderRight, value)
    }
    pub fn border_bottom(self, value: Border) -> Self {
        self.with(StyleProperty::BorderBottom, value)
    }
    pub fn border_left(self, value: Border) -> Self {
        self.with(StyleProperty::BorderLeft, value)
    }
    pub fn border_radius(self, value: CornerRadii) -> Self {
        self.with(StyleProperty::BorderRadius, value)
    }
    pub fn cursor(self, value: Cursor) -> Self {
        self.with(StyleProperty::Cursor, value)
    }
    pub fn list_style(self, value: ListStyleType) -> Self {
        self.with(StyleProperty::ListStyleType, value)
    }
    pub fn transform(self, value: TransformList) -> Self {
        self.with(StyleProperty::Transform, value)
    }
    pub fn pointer_events(self, value: PointerEvents) -> Self {
        self.with(StyleProperty::PointerEvents, value)
    }
    pub fn direction(self, value: Direction) -> Self {
        self.with(StyleProperty::Direction, value)
    }
    pub fn font_kerning(self, value: FontKerning) -> Self {
        self.with(StyleProperty::FontKerning, value)
    }
    pub fn font_optical_sizing(self, value: FontOpticalSizing) -> Self {
        self.with(StyleProperty::FontOpticalSizing, value)
    }
    pub fn font_palette(self, value: FontPalette) -> Self {
        self.with(StyleProperty::FontPalette, value)
    }
    pub fn font_size_adjust(self, value: FontSizeAdjust) -> Self {
        self.with(StyleProperty::FontSizeAdjust, value)
    }
    pub fn font_stretch(self, value: FontStretch) -> Self {
        self.with(StyleProperty::FontStretch, value)
    }
    pub fn font_style(self, value: FontStyleEnum) -> Self {
        self.with(StyleProperty::FontStyle, value)
    }
    pub fn font_variant_ligatures(self, value: FontVariantLigatures) -> Self {
        self.with(StyleProperty::FontVariantLigatures, value)
    }
    pub fn font_variant_caps(self, value: FontVariantCaps) -> Self {
        self.with(StyleProperty::FontVariantCaps, value)
    }
    pub fn font_variant_east_asian(self, value: FontVariantEastAsian) -> Self {
        self.with(StyleProperty::FontVariantEastAsian, value)
    }
    pub fn font_variant_numeric(self, value: FontVariantNumeric) -> Self {
        self.with(StyleProperty::FontVariantNumeric, value)
    }
    pub fn font_variant_alternates(self, value: FontVariantAlternates) -> Self {
        self.with(StyleProperty::FontVariantAlternates, value)
    }
    pub fn font_variant_position(self, value: FontVariantPosition) -> Self {
        self.with(StyleProperty::FontVariantPosition, value)
    }
    pub fn font_variant_emoji(self, value: FontVariantEmoji) -> Self {
        self.with(StyleProperty::FontVariantEmoji, value)
    }
    pub fn font_synthesis_weight(self, value: FontSynthesis) -> Self {
        self.with(StyleProperty::FontSynthesisWeight, value)
    }
    pub fn font_synthesis_style(self, value: FontSynthesis) -> Self {
        self.with(StyleProperty::FontSynthesisStyle, value)
    }
    pub fn font_synthesis_small_caps(self, value: FontSynthesis) -> Self {
        self.with(StyleProperty::FontSynthesisSmallCaps, value)
    }
    pub fn font_synthesis_position(self, value: FontSynthesis) -> Self {
        self.with(StyleProperty::FontSynthesisPosition, value)
    }
    pub fn font_feature_settings(self, value: OpenTypeFeatureList) -> Self {
        self.with(StyleProperty::FontFeatureSettings, value)
    }
    pub fn font_variation_settings(self, value: FontVariationList) -> Self {
        self.with(StyleProperty::FontVariationSettings, value)
    }
    pub fn font_language_override(self, value: FontLanguageOverride) -> Self {
        self.with(StyleProperty::FontLanguageOverride, value)
    }
    pub fn line_height(self, value: LineHeight) -> Self {
        self.with(StyleProperty::LineHeight, value)
    }
    pub fn letter_spacing(self, value: f32) -> Self {
        self.with(StyleProperty::LetterSpacing, value)
    }
    pub fn word_spacing(self, value: f32) -> Self {
        self.with(StyleProperty::WordSpacing, value)
    }
    pub fn text_indent(self, value: LengthValue) -> Self {
        self.with(StyleProperty::TextIndent, value)
    }
    pub fn text_align(self, value: TextAlign) -> Self {
        self.with(StyleProperty::TextAlign, value)
    }
    pub fn text_align_last(self, value: TextAlignLast) -> Self {
        self.with(StyleProperty::TextAlignLast, value)
    }
    pub fn text_justify(self, value: TextJustify) -> Self {
        self.with(StyleProperty::TextJustify, value)
    }
    pub fn word_break(self, value: WordBreak) -> Self {
        self.with(StyleProperty::WordBreak, value)
    }
    pub fn overflow_wrap(self, value: OverflowWrap) -> Self {
        self.with(StyleProperty::OverflowWrap, value)
    }
    pub fn word_wrap(self, value: OverflowWrap) -> Self {
        self.with(StyleProperty::WordWrap, value)
    }
    pub fn line_break(self, value: LineBreak) -> Self {
        self.with(StyleProperty::LineBreak, value)
    }
    pub fn hyphens(self, value: Hyphens) -> Self {
        self.with(StyleProperty::Hyphens, value)
    }
    pub fn hyphenate_limit_chars(self, value: HyphenationLimits) -> Self {
        self.with(StyleProperty::HyphenateLimitChars, value)
    }
    pub fn hyphenate_character(self, value: HyphenateCharacter) -> Self {
        self.with(StyleProperty::HyphenateCharacter, value)
    }
    pub fn white_space_collapse(self, value: WhiteSpaceCollapse) -> Self {
        self.with(StyleProperty::WhiteSpaceCollapse, value)
    }
    pub fn text_wrap_mode(self, value: TextWrapMode) -> Self {
        self.with(StyleProperty::TextWrapMode, value)
    }
    pub fn text_wrap_style(self, value: TextWrapStyle) -> Self {
        self.with(StyleProperty::TextWrapStyle, value)
    }
    pub fn text_autospace(self, value: TextAutospace) -> Self {
        self.with(StyleProperty::TextAutospace, value)
    }
    pub fn text_spacing_trim(self, value: TextSpacingTrim) -> Self {
        self.with(StyleProperty::TextSpacingTrim, value)
    }
    pub fn tab_size(self, value: TabSize) -> Self {
        self.with(StyleProperty::TabSize, value)
    }
    pub fn text_transform(self, value: TextTransform) -> Self {
        self.with(StyleProperty::TextTransform, value)
    }
    pub fn text_decoration_line(self, value: TextDecorationLine) -> Self {
        self.with(StyleProperty::TextDecorationLine, value)
    }
    pub fn text_decoration_style(self, value: TextDecorationStyle) -> Self {
        self.with(StyleProperty::TextDecorationStyle, value)
    }
    pub fn text_decoration_color(self, value: StyleColor) -> Self {
        self.with(StyleProperty::TextDecorationColor, value)
    }
    pub fn text_decoration_thickness(self, value: TextDecorationThickness) -> Self {
        self.with(StyleProperty::TextDecorationThickness, value)
    }
    pub fn text_decoration_skip_ink(self, value: TextDecorationSkipInk) -> Self {
        self.with(StyleProperty::TextDecorationSkipInk, value)
    }
    pub fn text_underline_offset(self, value: LengthValue) -> Self {
        self.with(StyleProperty::TextUnderlineOffset, value)
    }
    pub fn text_underline_position(self, value: TextUnderlinePosition) -> Self {
        self.with(StyleProperty::TextUnderlinePosition, value)
    }
    pub fn text_emphasis_style(self, value: TextEmphasisStyle) -> Self {
        self.with(StyleProperty::TextEmphasisStyle, value)
    }
    pub fn text_emphasis_position(self, value: TextEmphasisPosition) -> Self {
        self.with(StyleProperty::TextEmphasisPosition, value)
    }
    pub fn text_emphasis_color(self, value: StyleColor) -> Self {
        self.with(StyleProperty::TextEmphasisColor, value)
    }
    pub fn text_shadow(self, value: TextShadowList) -> Self {
        self.with(StyleProperty::TextShadow, value)
    }
    pub fn text_overflow(self, value: TextOverflow) -> Self {
        self.with(StyleProperty::TextOverflow, value)
    }
    pub fn text_size_adjust(self, value: TextSizeAdjust) -> Self {
        self.with(StyleProperty::TextSizeAdjust, value)
    }
    pub fn text_combine_upright(self, value: TextCombineUpright) -> Self {
        self.with(StyleProperty::TextCombineUpright, value)
    }
    pub fn writing_mode(self, value: WritingMode) -> Self {
        self.with(StyleProperty::WritingMode, value)
    }
    pub fn text_orientation(self, value: TextOrientation) -> Self {
        self.with(StyleProperty::TextOrientation, value)
    }
    pub fn unicode_bidi(self, value: UnicodeBidi) -> Self {
        self.with(StyleProperty::UnicodeBidi, value)
    }
    pub fn vertical_align(self, value: VerticalAlign) -> Self {
        self.with(StyleProperty::VerticalAlign, value)
    }
    pub fn ruby_align(self, value: RubyAlign) -> Self {
        self.with(StyleProperty::RubyAlign, value)
    }
    pub fn ruby_position(self, value: RubyPosition) -> Self {
        self.with(StyleProperty::RubyPosition, value)
    }
    pub fn ruby_overhang(self, value: RubyOverhang) -> Self {
        self.with(StyleProperty::RubyOverhang, value)
    }
    pub fn hanging_punctuation(self, value: HangingPunctuation) -> Self {
        self.with(StyleProperty::HangingPunctuation, value)
    }
    pub fn initial_letter(self, value: InitialLetterValue) -> Self {
        self.with(StyleProperty::InitialLetter, value)
    }
    pub fn text_rendering(self, value: TextRendering) -> Self {
        self.with(StyleProperty::TextRendering, value)
    }
    pub fn webkit_font_smoothing(self, value: FontSmoothing) -> Self {
        self.with(StyleProperty::WebkitFontSmoothing, value)
    }
    pub fn line_clamp(self, value: LineClamp) -> Self {
        self.with(StyleProperty::LineClamp, value)
    }
    pub fn block_ellipsis(self, value: BlockEllipsis) -> Self {
        self.with(StyleProperty::BlockEllipsis, value)
    }
    pub fn text_box_edge(self, value: TextBoxEdge) -> Self {
        self.with(StyleProperty::TextBoxEdge, value)
    }
    pub fn text_box_trim(self, value: TextBoxTrim) -> Self {
        self.with(StyleProperty::TextBoxTrim, value)
    }
    pub fn font(self, value: FontShorthand) -> Self {
        self.with(StyleProperty::Font, value)
    }
    pub fn font_variant(self, value: FontVariantShorthand) -> Self {
        self.with(StyleProperty::FontVariant, value)
    }
    pub fn font_synthesis(self, value: FontSynthesisShorthand) -> Self {
        self.with(StyleProperty::FontSynthesis, value)
    }
    pub fn white_space(self, value: WhiteSpaceShorthand) -> Self {
        self.with(StyleProperty::WhiteSpace, value)
    }
    pub fn text_wrap(self, value: TextWrapShorthand) -> Self {
        self.with(StyleProperty::TextWrap, value)
    }
    pub fn text_decoration(self, value: TextDecorationShorthand) -> Self {
        self.with(StyleProperty::TextDecoration, value)
    }
    pub fn text_emphasis(self, value: TextEmphasisShorthand) -> Self {
        self.with(StyleProperty::TextEmphasis, value)
    }
    pub fn text_box(self, value: TextBoxShorthand) -> Self {
        self.with(StyleProperty::TextBox, value)
    }
}
